// Which small subgroups of W(F4) force the husk transport isotropic, and to what order (E-RLT-0063).
//
// E-RLT-0058 found W(F4) forces the husk scalar transport (diffusion, sound) isotropic through k^4 and the
// husk shear at leading order, because its only quartic invariant is |k|^4. A knit need not carry all 1,152
// elements for the scalar law: any group whose invariant quartics are all multiples of |k|^4 gives it. This
// module censuses every subgroup of W(F4) generated by two elements (one from each conjugacy class, the other
// any element), up to a given order, and asks code/measure/husk-transport-symmetry forcedIsotropic of each:
// bulk scalars at degrees 2 and 4 (which force the husk ones at every orientation), husk scalars at degree 4
// and 6, and the husk shear at its leading degree (2 in the polarization, 2 in k). It also counts how many
// line-momentum forms exact local color would freeze under each (code/measure/color-isotropy-bound
// forcedForms), which E-RLT-0051 bounds below by 8 for every irreducible group.

import { type GroupTable, forcedForms } from '@/code/measure/color-isotropy-bound'
import { conjugacyClasses } from '@/code/measure/glide-group'
import { forcedIsotropic, matrixOfPermutation, type Matrix4 } from '@/code/measure/husk-transport-symmetry'

// the subgroup generated by gens, or undefined once it passes `cap` elements
export function cappedClosure(table: GroupTable, gens: readonly number[], cap: number): number[] | undefined {
  const n = table.permutations.length
  const seen = new Set<number>([table.identity])
  const queue = [table.identity]

  while (queue.length > 0) {
    const x = queue.pop() ?? 0

    for (const g of gens) {
      const y = table.multiply[g * n + x] ?? 0

      if (!seen.has(y)) {
        if (seen.size >= cap) return undefined

        seen.add(y)
        queue.push(y)
      }
    }
  }

  return [...seen].sort((a, b) => a - b)
}

// every distinct two-generated subgroup of order at most `cap`
export function twoGeneratedSubgroups(table: GroupTable, cap: number): number[][] {
  const { representatives } = conjugacyClasses(table.permutations)
  const n = table.permutations.length
  const found = new Map<string, number[]>()

  for (const a of representatives) {
    for (let b = 0; b < n; b++) {
      const g = cappedClosure(table, [a, b], cap)

      if (g) found.set(g.join(','), g)
    }
  }

  return [...found.values()]
}

// the conjugacy class of a subgroup, as the least sorted key over its conjugates
export function subgroupClassKey(table: GroupTable, group: readonly number[]): string {
  const n = table.permutations.length
  let best = ''

  for (let h = 0; h < n; h++) {
    const k = group.map(x => table.multiply[(table.multiply[h * n + x] ?? 0) * n + (table.inverse[h] ?? 0)] ?? 0).sort((p, q) => p - q)
    const key = k.join(',')

    if (best === '' || key < best) best = key
  }

  return best
}

export type ForcingReport = {
  readonly order: number
  // forced isotropic: bulk scalars of degree 2 and 4, husk scalars of degree 4 and 6, husk shear at degree 2
  readonly bulk2: boolean
  readonly bulk4: boolean
  readonly husk4: boolean
  readonly husk6: boolean
  readonly huskShear2: boolean
  // how many line-momentum forms exact local color freezes under the group (P and every image of D)
  readonly colorForms: number
  // whether the group acts on the 24 slots with no slot fixed by a non-identity element (freely)
  readonly free: boolean
}

export function forcingReport(table: GroupTable, group: readonly number[]): ForcingReport {
  const matrices: Matrix4[] = group.map(i => matrixOfPermutation(table.permutations[i] ?? []))
  const forced = (kind: 'scalar' | 'transverse', degree: number, husk: boolean): boolean => forcedIsotropic({ group: matrices, kind, degree, husk }).forced
  const free = group.every(i => i === table.identity || (table.permutations[i] ?? []).every((image, d) => image !== d))

  return {
    order: group.length,
    bulk2: forced('scalar', 2, false),
    bulk4: forced('scalar', 4, false),
    husk4: forced('scalar', 4, true),
    husk6: forced('scalar', 6, true),
    huskShear2: forced('transverse', 2, true),
    colorForms: forcedForms(table, group).length,
    free,
  }
}
