// Deterministic probe direction sets for isotropy and dispersion-anisotropy tests.
// No random seed is used: the directions are reproducible, so the same set is
// available across runs and substrates.

// The 2 * dimension signed coordinate axes (+e_i and -e_i for each axis), the
// coarse "cubic" direction set. For dimension 4 this is the 8 hyper-cubic axes.
export function coordinateAxes(dimension: number): number[][] {
  const axes: number[][] = []
  for (let index = 0; index < dimension; index++) {
    for (const sign of [1, -1]) {
      const axis = new Array<number>(dimension).fill(0)
      axis[index] = sign
      axes.push(axis)
    }
  }

  return axes
}

// A deterministic, well-spread set of unit probe directions on the unit sphere in
// `dimension` dimensions, generated by an additive recurrence (a low-discrepancy
// Kronecker sequence) and normalised. Used to sample how isotropic a dispersion or
// direction field is at a given scale, without any random seed. `dimension` may be 3
// or 4 (the irrational multipliers below cover up to four axes).
export function probeDirections(input: {
  count: number
  dimension: number
}): number[][] {
  const { count, dimension } = input
  const alpha = [
    0.7548776662466927, 0.5698402909980532, 0.4301597090019468,
    0.3247179572447458,
  ]
  const directions: number[][] = []
  for (let index = 1; index <= count; index++) {
    const raw: number[] = []
    for (let axis = 0; axis < dimension; axis++) {
      raw.push(((index * (alpha[axis] ?? 0.5)) % 1) - 0.5)
    }

    const norm = Math.hypot(...raw)
    directions.push(raw.map(value => value / norm))
  }

  return directions
}
