// Deterministic probe direction sets for isotropy and dispersion-anisotropy tests.
// No random seed is used: the directions are reproducible, so the same set is
// available across runs and substrates.

// The 2 * dimension signed coordinate axes (+e_i and -e_i for each axis), the
// coarse "cubic" direction set. For dimension 4 this is the 8 hyper-cubic axes.
export function coordinateAxes(dimension: number): number[][] {
  const axes: number[][] = []

  for (let index = 0; index < dimension; index++) {
    for (const sign of [1, -1]) {
      const axis = new Array<number>(dimension).fill(0)
      axis[index] = sign
      axes.push(axis)
    }
  }

  return axes
}

// The generalised golden ratio for `dimension`: the unique positive root of
// x^(dimension+1) = x + 1. The per-axis multipliers of the Roberts R_d
// low-discrepancy sequence are its inverse powers. Computed by fixed-point
// iteration of x = (1 + x)^(1/(dimension+1)), which converges deterministically
// from any positive start. (dimension 1 gives the golden ratio, dimension 2 the
// plastic number, and so on.)
function generalisedGoldenRatio(dimension: number): number {
  const power = 1 / (dimension + 1)
  let phi = 2

  // 64 iterations is far past convergence to double precision for any small
  // dimension, and fixed so the value is bit-identical across runs.
  for (let step = 0; step < 64; step++) {
    phi = Math.pow(1 + phi, power)
  }

  return phi
}

// A deterministic, well-spread set of unit probe directions on the unit sphere in
// `dimension` dimensions, generated by the Roberts additive recurrence (a
// low-discrepancy Kronecker sequence) and normalised. Used to sample how isotropic
// a dispersion or direction field is at a given scale, without any random seed.
//
// The axis multipliers MUST be the inverse powers of the generalised golden ratio
// for THIS dimension. Using a single fixed ratio across dimensions (an earlier bug)
// collapsed the set: the plastic number rho satisfies rho^3 = rho + 1, so its powers
// give 1/rho^2 + 1/rho^3 = 1 exactly, which forced coordinate 3 to be the exact
// negative of coordinate 2 on every sample and folded the directions onto a plane.
// The per-dimension root has no such relation among the powers actually used.
export function probeDirections(input: {
  count: number
  dimension: number
}): number[][] {
  const { count, dimension } = input
  const phi = generalisedGoldenRatio(dimension)

  const alpha = new Array<number>(dimension)
  for (let axis = 0; axis < dimension; axis++) {
    alpha[axis] = Math.pow(phi, -(axis + 1))
  }

  const directions: number[][] = []

  for (let index = 1; index <= count; index++) {
    const raw: number[] = []

    for (let axis = 0; axis < dimension; axis++) {
      raw.push(((index * (alpha[axis] ?? 0.5)) % 1) - 0.5)
    }

    const norm = Math.hypot(...raw)
    directions.push(raw.map(value => value / norm))
  }

  return directions
}
