// A MEMBER THAT CARRIES A CLIFFORD REGISTER, AND THE SINGLET'S SPINOR PARTNER (E-SPN-0160). Each vibe of a dock holds,
// beside its slot (one of the 24 D4 roots), a register in the even Clifford algebra of the dock's 4d space,
// Cl+(4) = wedge^0 + wedge^2 + wedge^4 (8 components; as an algebra H + H, the one the 24 Hurwitz units, 2T, generate).
// W(F4) acts on a member as the root permutation times its natural action on forms (minors of the 4 x 4 matrix), a
// genuine (not projective) representation with dyadic entries. A member's one-vibe space is 24 x 8 = 192.
//
//   REGISTER            the blades of the even and odd forms, and the Clifford map gamma_i = e_i ^ + iota_i (even to
//                       odd), with gamma_i^T gamma_j + gamma_j^T gamma_i = 2 delta_ij (the Dirac-Kaehler structure)
//   singletProjector    Q_S = Pi1 (x) 1, the uniform slot mode times any register: the singlet sector, rank 8 (x 24
//                       an integer matrix)
//   partnerProjector    Q_D = Phi^dag Phi / 4 on Pi4 (x) register, Phi(a (x) w) = gamma(a) w: the image of the odd forms,
//                       the singlet's CLIFFORD partner, rank 8 (x 48 an integer matrix)
//   vectorProjector     Pi4 (x) 1, the whole vector partner (rank 32): the no-register pin, as a control
//   f4Group             the 1,152 elements of W(F4) (generated by the four simple reflections), each with its slot
//                       permutation and its 8 x 8 register action
//   commutesExactly     g Q = Q g on the 192 modes, in exact arithmetic (integers and dyadics)
//   registerPiece       P = X (1 + (u - 1) Q): a mixer on the sector Q after the swap coin (X the slot reversal, which
//                       acts trivially on even forms)
//   diracPhase          THE EXACT BAND of the schedule (beat 1 the mixer u on Q_S, beat 2 the mixer conj(u) on Q_D): the
//                       cycle on span(S, T D) is eight copies of a 2 x 2 walk, cos E = cos M - 2 cos^2(M / 2) g^2,
//                       g = |s(K)| / 2, s(K) = sum_r r sin(K . r) / sqrt 288, around the midpoint pi; every other band
//                       is flat at phase 0
//   the generic readers  the census, flats, frame R and massless pair of code/measure/two-beat with the root table as an
//                       argument (the 24-slot ones read DOCK_ROOTS); with DOCK_ROOTS they reproduce those bit for bit
//                       (the experiment's control)
//
// DETERMINISM: no random numbers. EXACT: every projector and every group element is an integer or a dyadic matrix, so
// the exact checks run in double arithmetic without rounding (every value below 2^30). Floats elsewhere, as measurement.

import { complexEigenvalues } from '@/code/algebra/linear/complex-eigen'
import {
  DOCK_ROOTS,
  wrap,
  type CMatrix,
} from '@/code/measure/dock-mixer'
import { cyclePhases } from '@/code/measure/swap-cone'
import { polynomialAtZero } from '@/code/measure/singlet-kinematics'
import {
  type Census,
  type FamilyCensus,
  type Frame,
  type HMat,
} from '@/code/measure/two-beat'
import { OPPOSITE } from '@/code/rule/isometric-knit'

type Roots = readonly (readonly number[])[]

const SLOTS = 24
const REG = 8

export const MODES = SLOTS * REG

const dot = (a: readonly number[], b: readonly number[]): number =>
  a.reduce((s, x, k) => s + x * b[k]!, 0)

// ---- the register: blades of wedge V, V = R^4 ----

export const EVEN: readonly (readonly number[])[] = [
  [],
  [0, 1],
  [0, 2],
  [0, 3],
  [1, 2],
  [1, 3],
  [2, 3],
  [0, 1, 2, 3],
]
export const ODD: readonly (readonly number[])[] = [
  [0],
  [1],
  [2],
  [3],
  [0, 1, 2],
  [0, 1, 3],
  [0, 2, 3],
  [1, 2, 3],
]

const bladeKey = (b: readonly number[]): string => b.join(',')

// e_i ^ e_B: the sign (-1)^(elements of B below i) and the sorted blade, or null when i is in B
function wedge(
  i: number,
  B: readonly number[],
): { sign: number; blade: number[] } | null {
  if (B.includes(i)) {
    return null
  }

  const below = B.filter(x => x < i).length

  return {
    sign: below % 2 === 0 ? 1 : -1,
    blade: [...B, i].sort((a, b) => a - b),
  }
}

// iota_i e_B: the sign (-1)^(position of i in B) and B without i, or null when i is not in B
function contract(
  i: number,
  B: readonly number[],
): { sign: number; blade: number[] } | null {
  const at = B.indexOf(i)

  if (at < 0) {
    return null
  }

  return { sign: at % 2 === 0 ? 1 : -1, blade: B.filter(x => x !== i) }
}

// gamma_i as an 8 x 8 integer matrix [odd row][even column]: gamma_i w = e_i ^ w + iota_i w for w even
export function gammaMatrices(): number[][][] {
  const oddIndex = new Map(ODD.map((b, k) => [bladeKey(b), k]))

  return [0, 1, 2, 3].map(i => {
    const g = Array.from({ length: REG }, () =>
      Array<number>(REG).fill(0),
    )

    EVEN.forEach((B, col) => {
      for (const t of [wedge(i, B), contract(i, B)]) {
        if (!t) {
          continue
        }

        g[oddIndex.get(bladeKey(t.blade))!]![col]! += t.sign
      }
    })

    return g
  })
}

// ---- the projectors (row-major 192 x 192, index slot * 8 + register) ----

export const REGISTER_ROOTS: Roots = Array.from(
  { length: MODES },
  (_, i) => DOCK_ROOTS[Math.floor(i / REG)]!,
)

// 24 Q_S: delta of the registers (every slot pair)
export function singletProjector24(): Float64Array {
  const q = new Float64Array(MODES * MODES)

  for (let d = 0; d < SLOTS; d++) {
    for (let e = 0; e < SLOTS; e++) {
      for (let a = 0; a < REG; a++) {
        q[(d * REG + a) * MODES + e * REG + a] = 1
      }
    }
  }

  return q
}

// 48 Q_D = sum_(i, j) r_i r'_j (gamma_i^T gamma_j)_(a a'): Q_D = sum over the odd blades eta of E(eta) E(eta)^T,
// E(eta) = Phi^dag eta / 2 = (1 / 2) sum_i f_i (x) gamma_i^T eta, f_i = sum_d r_d,i |d> / sqrt 12
export function partnerProjector48(): Float64Array {
  const g = gammaMatrices()
  const gg = Array.from({ length: 4 }, (_, i) =>
    Array.from({ length: 4 }, (_, j) =>
      Array.from({ length: REG }, (_, a) =>
        Array.from({ length: REG }, (_, b) =>
          g[i]!.reduce(
            (s, row, eta) => s + row[a]! * g[j]![eta]![b]!,
            0,
          ),
        ),
      ),
    ),
  )
  const q = new Float64Array(MODES * MODES)
  const R = DOCK_ROOTS

  for (let d = 0; d < SLOTS; d++) {
    for (let e = 0; e < SLOTS; e++) {
      for (let a = 0; a < REG; a++) {
        for (let b = 0; b < REG; b++) {
          let s = 0

          for (let i = 0; i < 4; i++) {
            for (let j = 0; j < 4; j++) {
              s +=
                (R[d] as number[])[i]! *
                (R[e] as number[])[j]! *
                gg[i]![j]![a]![b]!
            }
          }

          q[(d * REG + a) * MODES + e * REG + b] = s
        }
      }
    }
  }

  return q
}

// 12 (Pi4 (x) 1): the whole vector partner, (r . r') delta_ab
export function vectorProjector12(): Float64Array {
  const q = new Float64Array(MODES * MODES)

  for (let d = 0; d < SLOTS; d++) {
    for (let e = 0; e < SLOTS; e++) {
      for (let a = 0; a < REG; a++) {
        q[(d * REG + a) * MODES + e * REG + a] = dot(
          DOCK_ROOTS[d] as number[],
          DOCK_ROOTS[e] as number[],
        )
      }
    }
  }

  return q
}

export const scaled = (q: Float64Array, by: number): Float64Array =>
  q.map(x => x / by)

// the exact product of two scaled 192 x 192 matrices (integers and dyadics: no rounding below 2^53)
export function matMul(
  a: Float64Array,
  b: Float64Array,
  n = MODES,
): Float64Array {
  const o = new Float64Array(n * n)

  for (let i = 0; i < n; i++) {
    for (let k = 0; k < n; k++) {
      const x = a[i * n + k]!

      if (x === 0) {
        continue
      }

      for (let j = 0; j < n; j++) {
        o[i * n + j]! += x * b[k * n + j]!
      }
    }
  }

  return o
}

export const sameMatrix = (a: Float64Array, b: Float64Array): boolean =>
  a.every((x, i) => x === b[i])
export const trace = (a: Float64Array, n = MODES): number =>
  Array.from({ length: n }, (_, i) => a[i * n + i]!).reduce(
    (s, x) => s + x,
    0,
  )

// ---- W(F4) ----

export type GroupElement = {
  matrix: number[][]
  slots: Int32Array
  register: number[][]
}

// the four simple roots of F4 (long e2 - e3, e3 - e4; short e4, (e1 - e2 - e3 - e4) / 2)
const F4_SIMPLE: readonly number[][] = [
  [0, 1, -1, 0],
  [0, 0, 1, -1],
  [0, 0, 0, 1],
  [0.5, -0.5, -0.5, -0.5],
]

const reflection = (a: readonly number[]): number[][] => {
  const n = dot(a, a)

  return [0, 1, 2, 3].map(i =>
    [0, 1, 2, 3].map(j => (i === j ? 1 : 0) - (2 * a[i]! * a[j]!) / n),
  )
}

const mul4 = (
  a: readonly (readonly number[])[],
  b: readonly (readonly number[])[],
): number[][] =>
  [0, 1, 2, 3].map(i =>
    [0, 1, 2, 3].map(j =>
      [0, 1, 2, 3].reduce(
        (s, k) => s + (a[i] as number[])[k]! * (b[k] as number[])[j]!,
        0,
      ),
    ),
  )

// the determinant of the minor of g on rows `rows` and columns `cols` (sizes 0, 2, 4)
function minor(
  g: readonly (readonly number[])[],
  rows: readonly number[],
  cols: readonly number[],
): number {
  if (rows.length === 0) {
    return 1
  }

  if (rows.length === 1) {
    return (g[rows[0]!] as number[])[cols[0]!]!
  }

  let s = 0

  cols.forEach((c, k) => {
    const sub = minor(
      g,
      rows.slice(1),
      cols.filter((_, j) => j !== k),
    )

    s += (k % 2 === 0 ? 1 : -1) * (g[rows[0]!] as number[])[c]! * sub
  })

  return s
}

// the action on the even forms: g e_B = sum_B' det(g[B', B]) e_B'
export const evenAction = (
  g: readonly (readonly number[])[],
): number[][] =>
  EVEN.map(Bp =>
    EVEN.map(B => (Bp.length === B.length ? minor(g, Bp, B) : 0)),
  )

export function f4Group(): GroupElement[] {
  const gens = F4_SIMPLE.map(reflection)
  const key = (m: readonly (readonly number[])[]): string =>
    m.map(r => r.map(x => Math.round(2 * x)).join(',')).join(';')
  const seen = new Map<string, number[][]>()
  const I: number[][] = [0, 1, 2, 3].map(i =>
    [0, 1, 2, 3].map(j => (i === j ? 1 : 0)),
  )

  let frontier = [I]

  seen.set(key(I), I)

  while (frontier.length > 0) {
    const next: number[][][] = []

    for (const m of frontier) {
      for (const s of gens) {
        const x = mul4(s, m)
        const k = key(x)

        if (!seen.has(k)) {
          seen.set(k, x)
          next.push(x)
        }
      }
    }

    frontier = next
  }

  const rootIndex = new Map(DOCK_ROOTS.map((r, d) => [r.join(','), d]))

  return [...seen.values()].map(matrix => {
    const slots = new Int32Array(SLOTS)

    DOCK_ROOTS.forEach((r, d) => {
      const image = [0, 1, 2, 3].map(i =>
        matrix[i]!.reduce((s, x, k) => s + x * r[k]!, 0),
      )

      slots[d] = rootIndex.get(image.join(',')) ?? -1
    })

    return { matrix, slots, register: evenAction(matrix) }
  })
}

// g Q = Q g exactly, g acting on (slot d, register b) as (slots[d], register[a][b])
export function commutesExactly(
  g: GroupElement,
  q: Float64Array,
): boolean {
  const n = MODES

  // g maps (d, b) to (slots[d], a) with weight register[a][b]; compare (g Q) and (Q g) at every entry ((slots[d], a),
  // (e, c)): (g Q) there is sum_b register[a][b] Q[(d, b), (e, c)], (Q g) there is sum_b Q[(slots[d], a), (slots[e],
  // b)] register[b][c]
  for (let d = 0; d < SLOTS; d++) {
    const sd = g.slots[d]!

    for (let e = 0; e < SLOTS; e++) {
      const se = g.slots[e]!

      for (let a = 0; a < REG; a++) {
        for (let c = 0; c < REG; c++) {
          // left: (g Q)[(sd, a), (e, c)] = sum_b reg[a][b] Q[(d, b), (e, c)]
          let left = 0

          for (let b = 0; b < REG; b++) {
            left +=
              g.register[a]![b]! * q[(d * REG + b) * n + e * REG + c]!
          }

          // right: (Q g)[(sd, a), (e, c)] = sum_b Q[(sd, a), (se, b)] reg[b][c]
          let right = 0

          for (let b = 0; b < REG; b++) {
            right +=
              q[(sd * REG + a) * n + se * REG + b]! * g.register[b]![c]!
          }

          if (left !== right) {
            return false
          }
        }
      }
    }
  }

  return true
}

// ---- the pieces and the cycle ----

// P = X (1 + (u - 1) Q), row-major [to][from]; X sends slot d to its opposite and keeps the register (-1 acts on the
// even forms as the identity)
export function registerPiece(
  q: Float64Array,
  u: readonly [number, number],
): CMatrix {
  const n = MODES
  const re = new Float64Array(n * n)
  const im = new Float64Array(n * n)

  for (let i = 0; i < n; i++) {
    const from = OPPOSITE[Math.floor(i / REG)]! * REG + (i % REG)

    for (let j = 0; j < n; j++) {
      const x = q[from * n + j]!

      re[i * n + j] = (from === j ? 1 : 0) + (u[0] - 1) * x
      im[i * n + j] = u[1] * x
    }
  }

  return { re, im }
}

// s(K) = sum_r r sin(K . r) / sqrt 288, the Pi4 content of T^dag z (times -i), and g = |s| / 2
export function structureVector(K: readonly number[]): number[] {
  const s = [0, 0, 0, 0]

  for (const r of DOCK_ROOTS) {
    const x = Math.sin(dot(K, r))

    for (let k = 0; k < 4; k++) {
      s[k]! += r[k]! * x
    }
  }

  return s.map(x => x / Math.sqrt(288))
}

// E(K), the S band's phase from the midpoint pi, per CYCLE (two beats), for the half gap M
export function diracPhase(K: readonly number[], M: number): number {
  const g2 = structureVector(K).reduce((a, x) => a + x * x, 0) / 4

  return Math.acos(Math.cos(M) - 2 * Math.cos(M / 2) ** 2 * g2)
}

// |grad E| per BEAT (half the cycle's): E = acos(c - k g^2), grad E = k grad(g^2) / sin E, grad(g^2) = J^T s / 2,
// J = sum_r r r^T cos(K . r) / sqrt 288
export function diracSpeed(K: readonly number[], M: number): number {
  const s = structureVector(K)
  const grad = [0, 0, 0, 0]

  for (const r of DOCK_ROOTS) {
    const c = Math.cos(dot(K, r)) / Math.sqrt(288)
    const rs = dot(r, s)

    for (let k = 0; k < 4; k++) {
      grad[k]! += r[k]! * rs * c
    }
  }

  const E = diracPhase(K, M)
  const kap = 2 * Math.cos(M / 2) ** 2
  const sinE = Math.sin(E)

  if (sinE < 1e-12) {
    return 0
  }

  return (kap * Math.hypot(...grad)) / 2 / sinE / 2
}

// ---- the generic readers (code/measure/two-beat's, with the root table an argument) ----

export const epsOfN = (
  Ps: readonly CMatrix[],
  f: Frame,
  q: readonly number[],
  roots: Roots,
): number[] =>
  cyclePhases(Ps, roots, q).map(ph => f.sign * -wrap(ph - f.mid))

export function trackedEpsN(
  Ps: readonly CMatrix[],
  f: Frame,
  path: readonly (readonly number[])[],
  roots: Roots,
): number[][] {
  const N = roots.length
  const out: number[][] = []

  let prev: number[] | null = null

  for (const q of path) {
    const raw = epsOfN(Ps, f, q, roots)

    if (!prev) {
      prev = [...raw].sort((a, b) => a - b)
      out.push(prev)
      continue
    }

    const cand: { i: number; j: number; d: number }[] = []

    for (let i = 0; i < N; i++) {
      for (let j = 0; j < N; j++) {
        cand.push({ i, j, d: Math.abs(wrap(raw[j]! - prev[i]!)) })
      }
    }

    cand.sort((a, b) => a.d - b.d)

    const next = Array<number>(N).fill(NaN)
    const used = new Uint8Array(N)

    for (const c of cand) {
      if (!Number.isNaN(next[c.i]!) || used[c.j]) {
        continue
      }

      next[c.i] = raw[c.j]!
      used[c.j] = 1
    }

    prev = next
    out.push(next)
  }

  return out
}

export function pairCensusN(
  Ps: readonly CMatrix[],
  f: Frame,
  paths: readonly (readonly (readonly number[])[])[],
  extra: readonly (readonly number[])[],
  roots: Roots,
  tol = 1e-9,
): Census {
  const N = roots.length

  let Bstar = Math.PI
  let at: number[] = []
  let pair: [number, number] = [NaN, NaN]
  let crossings = 0
  let first: Census['first'] = { q: Infinity, pair: [NaN, NaN] }

  const see = (
    eps: readonly number[],
    q: readonly number[],
  ): Float64Array => {
    const d = new Float64Array(N * N)

    for (let a = 0; a < N; a++) {
      for (let b = a; b < N; b++) {
        const x = wrap(2 * f.M - eps[a]! - eps[b]!)

        d[a * N + b] = x

        if (x > tol && x < Bstar) {
          Bstar = x
          at = [...q]
          pair = [eps[a]!, eps[b]!]
        }
      }
    }

    return d
  }

  for (const path of paths) {
    const bands = trackedEpsN(Ps, f, path, roots)
    const last = new Float64Array(N * N).fill(NaN)

    bands.forEach((eps, s) => {
      const d = see(eps, path[s]!)

      for (let a = 0; a < N; a++) {
        for (let b = a; b < N; b++) {
          const y = d[a * N + b]!
          const x = last[a * N + b]!

          if (Math.abs(y) <= tol) {
            continue
          }

          if (Math.abs(y) >= 1) {
            last[a * N + b] = NaN
            continue
          }

          if (!Number.isNaN(x) && x > 0 !== y > 0) {
            crossings++

            const r = Math.hypot(...path[s]!)

            if (r < first.q) {
              first = { q: r, pair: [eps[a]!, eps[b]!] }
            }
          }

          last[a * N + b] = y
        }
      }
    })
  }

  for (const q of extra) {
    see(epsOfN(Ps, f, q, roots), q)
  }

  return {
    M: f.M,
    Bstar: crossings > 0 ? 0 : Bstar,
    crossings,
    at,
    pair,
    first,
  }
}

export function cycleFlatsN(
  Ps: readonly CMatrix[],
  momenta: readonly (readonly number[])[],
  tol: number,
  roots: Roots,
): { phase: number; count: number }[] {
  const phs = momenta.map(K => cyclePhases(Ps, roots, K))
  const out: { phase: number; count: number }[] = []

  for (const p of [...phs[0]!].sort((a, b) => a - b)) {
    if (out.some(o => Math.abs(wrap(o.phase - p)) <= tol)) {
      continue
    }

    const count = Math.min(
      ...phs.map(
        ph => ph.filter(x => Math.abs(wrap(x - p)) <= tol).length,
      ),
    )

    if (count > 0) {
      out.push({ phase: p, count })
    }
  }

  return out
}

export function frameRN(
  Ps: readonly CMatrix[],
  f: Frame,
  sPhase: number,
  u: readonly number[],
  cStar: number,
  scales: readonly number[],
  roots: Roots,
): { m: number; c2: number; R: number } {
  const beats = Ps.length
  const m = f.M / beats
  const xs = scales.map(s => s * s)
  const ys = scales.map(s => {
    const K = s * m
    const near = cyclePhases(
      Ps,
      roots,
      u.map(x => x * K),
    ).reduce((b, ph) =>
      Math.abs(wrap(ph - sPhase)) < Math.abs(wrap(b - sPhase)) ? ph : b,
    )
    const e = (f.sign * -wrap(near - f.mid)) / beats

    return (e * e - m * m) / (K * K)
  })
  const c2 = polynomialAtZero(xs, ys).value

  return { m, c2, R: (cStar * cStar) / c2 }
}

export function cycleMasslessPairN(
  Ps: readonly CMatrix[],
  rest: number,
  u: readonly number[],
  kappa: number,
  roots: Roots,
  tol = 1e-9,
): { c0: number; gamma: number; size: number } {
  const beats = Ps.length
  const at0 = cyclePhases(Ps, roots, [0, 0, 0, 0])
  const size = at0.filter(ph => Math.abs(wrap(ph - rest)) <= tol).length

  const read = (k: number): { c: number; g: number } => {
    const ph = cyclePhases(
      Ps,
      roots,
      u.map(x => x * k),
    )
    const e = ph
      .map(x => wrap(x - rest))
      .sort((a, b) => Math.abs(a) - Math.abs(b))
      .slice(0, size)
      .map(x => -x / beats)
    const top = Math.max(...e)
    const bottom = Math.min(...e)

    return {
      c: (top - bottom) / (2 * k),
      g: (top + bottom) / (2 * k * k),
    }
  }

  const a = read(kappa)
  const b = read(kappa / 2)

  return { c0: (4 * b.c - a.c) / 3, gamma: (4 * b.g - a.g) / 3, size }
}

// code/measure/two-beat familyCensus with the size an argument
export function familyCensusN(
  B: HMat,
  As: readonly HMat[],
  P: number,
  n: number,
  N: number,
  tol = 1e-9,
): FamilyCensus {
  let Bstar = Infinity
  let crossings = 0
  let pair: [number, number] = [NaN, NaN]
  let at = NaN
  let first = Infinity

  for (const A of As) {
    const last = new Float64Array(N * N).fill(NaN)

    for (let j = 1; j <= n; j++) {
      const s = (P * j) / n
      const re = new Float64Array(N * N)
      const im = new Float64Array(N * N)

      for (let i = 0; i < N * N; i++) {
        re[i] = B.re[i]! + s * A.re[i]!
        im[i] = B.im[i]! + s * A.im[i]!
      }

      const e = [...complexEigenvalues({ re, im, n: N }).re].sort(
        (a, b) => a - b,
      )

      for (let a = 0; a < N; a++) {
        for (let b = a; b < N; b++) {
          const y = 2 - e[a]! - e[b]!
          const w = last[a * N + b]!

          if (y > tol && y < Bstar) {
            Bstar = y
            pair = [e[a]!, e[b]!]
            at = s
          }

          if (Math.abs(y) <= tol) {
            continue
          }

          if (!Number.isNaN(w) && w > 0 !== y > 0) {
            crossings++
            first = Math.min(first, s)
          }

          last[a * N + b] = y
        }
      }
    }
  }

  return {
    Bstar: crossings > 0 ? 0 : Bstar,
    crossings,
    pair,
    at,
    first,
  }
}

// ---- the continuum cluster of a register sector pair ----

// an orthonormal basis (columns) of the range of a projector (a Gram-Schmidt pass over its columns)
export function rangeBasis(q: Float64Array, n = MODES): number[][] {
  const out: number[][] = []

  for (let j = 0; j < n; j++) {
    let v = Array.from({ length: n }, (_, i) => q[i * n + j]!)

    for (const e of out) {
      const c = dot(v, e)

      v = v.map((x, i) => x - c * e[i]!)
    }

    const norm = Math.hypot(...v)

    if (norm > 1e-9) {
      out.push(v.map(x => x / norm))
    }
  }

  return out
}

// THE CLUSTER FAMILY of a singlet sector S (resting at +1) and a partner sector D (at -1): B = diag(+1, -1) and, along
// each direction u, A_u = the first-order stream X_u = diag(u . r) in the basis S then D, scaled by `speed` (its
// singular values times speed are |u| for a Clifford partner). H(p) = B + p A_u
export function clusterFamily(
  S: readonly number[][],
  D: readonly number[][],
  dirs: readonly (readonly number[])[],
  speed: number,
): { B: HMat; As: HMat[]; n: number } {
  const basis = [...S, ...D]
  const n = basis.length
  const B: HMat = {
    re: new Float64Array(n * n),
    im: new Float64Array(n * n),
  }

  basis.forEach((_, i) => {
    B.re[i * n + i] = i < S.length ? 1 : -1
  })

  const As = dirs.map(u => {
    const A: HMat = {
      re: new Float64Array(n * n),
      im: new Float64Array(n * n),
    }
    const w = REGISTER_ROOTS.map(r => dot(u, r))

    for (let i = 0; i < n; i++) {
      for (let j = 0; j < n; j++) {
        const bi = basis[i]!
        const bj = basis[j]!

        let s = 0

        for (let k = 0; k < MODES; k++) {
          s += bi[k]! * w[k]! * bj[k]!
        }

        A.re[i * n + j] = s * speed
      }
    }

    return A
  })

  return { B, As, n }
}

// the capture of the stream by a partner sector: for each unit direction u, |Q_D X_u Q_S|^2 against |X_u Q_S|^2 on the
// singlet sector, and how far Q_S X_u Q_D X_u Q_S is from a multiple of Q_S (the Clifford condition, S side) and
// Q_D X_u Q_S X_u Q_D from a multiple of Q_D (D side)
export function capture(
  qS: Float64Array,
  qD: Float64Array,
  u: readonly number[],
): { share: number; sideS: number; sideD: number } {
  const n = MODES
  const w = REGISTER_ROOTS.map(r => dot(u, r))
  // T = Q_D X Q_S
  const XQS = qS.map((x, i) => x * w[Math.floor(i / n)]!)
  const T = matMul(qD, XQS)
  const Tt = new Float64Array(n * n)

  for (let i = 0; i < n; i++) {
    for (let j = 0; j < n; j++) {
      Tt[j * n + i] = T[i * n + j]!
    }
  }

  const TtT = matMul(Tt, T)
  const TTt = matMul(T, Tt)
  const XQSt = new Float64Array(n * n)

  for (let i = 0; i < n; i++) {
    for (let j = 0; j < n; j++) {
      XQSt[j * n + i] = XQS[i * n + j]!
    }
  }

  const full = matMul(XQSt, XQS)
  const rS = trace(TtT) / trace(qS)
  const rD = trace(TTt) / trace(qD)

  let sideS = 0
  let sideD = 0

  for (let i = 0; i < n * n; i++) {
    sideS = Math.max(sideS, Math.abs(TtT[i]! - rS * qS[i]!))
    sideD = Math.max(sideD, Math.abs(TTt[i]! - rD * qD[i]!))
  }

  return { share: trace(TtT) / trace(full), sideS, sideD }
}

// the Weyl directions on the 3-sphere (unit vectors), additive recurrence on 1 / phi_5^k
export function weylDirections(count: number): number[][] {
  let phi = 1.5

  for (let i = 0; i < 64; i++) {
    phi = phi - (phi ** 5 - phi - 1) / (5 * phi ** 4 - 1)
  }

  const alpha = [1, 2, 3, 4].map(k => 1 / phi ** k)

  return Array.from({ length: count }, (_, j) => {
    const v = alpha.map(a => 2 * (((0.5 + (j + 1) * a) % 1) - 0.5))
    const norm = Math.hypot(...v)

    return v.map(x => x / norm)
  })
}
