// Which orientations of a covering store can a transport-forcing group keep (E-RLT-0094). MEASUREMENT: exact integer
// and group computations; the forcing test is code/measure/varying-vacuum huskForcing.
//
// THE QUESTION. A store pattern forces isotropic husk transport through the linear parts of the affine maps
// (g, t, c) that keep its ORIENTED units (E-RLT-0080). The hub pattern keeps 576 and forces the scalars and the shear.
// A pattern whose vacuum pairs visit every dock must store on a root dock more than the one line toward class 0
// (E-RLT-0093), and a stabilizer that fixes two stored lines at a dock must act on both with the same sign, the
// charge sign c. That is the obstruction measured here.
//
// THE CENSUS.
//  - every subgroup of W(F4) generated by two elements (the first a conjugacy class representative), and those
//    forcing the husk scalars (rank 2 and 4) and the shear; the minimal ones by inclusion; every conjugate of them
//  - every subgroup generated by three elements (a non-forcing two-generated group plus one element) that forces,
//    checked to contain a forcing two-generated conjugate
//  - for a W(F4)-invariant and L'-periodic unoriented pattern (the union), a group keeps an orientation only if the
//    lifts of its generators (each element g as x -> g x + t, t in L' mod 4 D4, with c = +-1: every affine symmetry
//    of the unoriented pattern with linear part g) do: tested for every lift pair of each minimal forcing group
//  - for a pattern that is not W(F4)-invariant, the set O of elements with a lift keeping some orientation alone, and
//    every subgroup inside O (an orientation-keeping group lies inside O); its forcing
//
// NOTHING MOVES: the file reads stores and groups; no rule runs here.

import { closure } from '@/code/measure/color-isotropy-bound'
import { huskForcing, translate, type AffineGenerator, type BoxMaps, type CoinData } from '@/code/measure/varying-vacuum'
import { NORM4, orientUnits } from '@/code/measure/dense-hub'
import { rootsD4 } from '@/code/algebra/group/root-system'
import { LINE_OF } from '@/code/rule/isometric-knit'
import { d4Coordinates } from '@/code/substrate/d4-box'

export type Subgroup = { readonly gens: number[]; readonly members: number[] }

export function fastClosure(coins: CoinData): (gens: readonly number[]) => number[] {
  const table = coins.table
  const n = table.permutations.length
  const mul = Int32Array.from(table.multiply as ArrayLike<number>)
  const mark = new Int32Array(n)
  const queue = new Int32Array(n)
  let epoch = 0

  return gens => {
    epoch++
    let head = 0
    let tail = 0

    mark[table.identity] = epoch
    queue[tail++] = table.identity

    while (head < tail) {
      const x = queue[head++] as number

      for (const g of gens) {
        const y = mul[g * n + x] as number

        if (mark[y] !== epoch) {
          mark[y] = epoch
          queue[tail++] = y
        }
      }
    }

    return Array.from(queue.subarray(0, tail)).sort((a, b) => a - b)
  }
}

export function classRepresentatives(coins: CoinData): number[] {
  const table = coins.table
  const n = table.permutations.length
  const seen = new Uint8Array(n)
  const reps: number[] = []

  for (let a = 0; a < n; a++) {
    if (seen[a]) continue

    reps.push(a)

    for (let g = 0; g < n; g++) seen[table.multiply[g * n + (table.multiply[a * n + (table.inverse[g] as number)] as number)] as number] = 1
  }

  return reps
}

export type ForcingCensus = {
  readonly classes: number
  readonly twoGenerated: number
  readonly forcingTwo: Subgroup[]
  readonly minimal: Subgroup[]
  readonly conjugates: number
  readonly threeClosures: number
  readonly threeDistinct: number
  readonly threeForcing: number
  readonly threeWithoutTwo: number
}

const forces = (coins: CoinData, members: readonly number[]): boolean => {
  if (members.length < 24) return false

  const f = huskForcing(coins, members)

  return f.husk2 && f.husk4 && f.huskShear2
}

export function forcingCensus(coins: CoinData, withThree: boolean): ForcingCensus {
  const table = coins.table
  const n = table.permutations.length
  const close = fastClosure(coins)
  const reps = classRepresentatives(coins)
  const two = new Map<string, Subgroup>()

  for (const a of reps) {
    for (let b = 0; b < n; b++) {
      const members = close([a, b])
      const key = members.join(',')

      if (!two.has(key)) two.set(key, { gens: [a, b], members })
    }
  }

  const cache = new Map<string, boolean>()
  const forcesCached = (members: number[]): boolean => {
    const key = members.join(',')
    let f = cache.get(key)

    if (f === undefined) {
      f = forces(coins, members)
      cache.set(key, f)
    }

    return f
  }
  const forcingTwo = [...two.values()].filter(G => forcesCached(G.members))
  const minimal = forcingTwo.filter(F => !forcingTwo.some(G => G !== F && G.members.length < F.members.length && G.members.every(m => F.members.includes(m))))
  const conjugateBits: Uint8Array[] = []
  const conjugateKeys = new Set<string>()

  for (const G of forcingTwo) {
    for (let g = 0; g < n; g++) {
      const gi = table.inverse[g] as number
      const bits = new Uint8Array(n)

      for (const m of G.members) bits[table.multiply[g * n + (table.multiply[m * n + gi] as number)] as number] = 1

      const key = Array.from(bits).join('')

      if (!conjugateKeys.has(key)) {
        conjugateKeys.add(key)
        conjugateBits.push(bits)
      }
    }
  }

  let threeClosures = 0
  let threeForcing = 0
  let threeWithoutTwo = 0
  const seen = new Set<string>()

  if (withThree) {
    for (const G of two.values()) {
      if (forcesCached(G.members)) continue

      const inG = new Uint8Array(n)

      for (const m of G.members) inG[m] = 1

      for (let c = 0; c < n; c++) {
        if (inG[c]) continue

        const K = close([...G.gens, c])
        const key = K.join(',')

        threeClosures++
        if (seen.has(key)) continue
        seen.add(key)

        if (!forcesCached(K)) continue

        threeForcing++

        const inK = new Uint8Array(n)

        for (const m of K) inK[m] = 1

        const contains = conjugateBits.some(bits => {
          for (let x = 0; x < n; x++) if (bits[x] && !inK[x]) return false

          return true
        })

        if (!contains) threeWithoutTwo++
      }
    }
  }

  return { classes: reps.length, twoGenerated: two.size, forcingTwo, minimal, conjugates: conjugateBits.length, threeClosures, threeDistinct: seen.size, threeForcing, threeWithoutTwo }
}

// every affine symmetry of an L'-periodic unoriented pattern with linear part g: x -> g x + t, t in `shifts`, c = +-1
export function liftsOf(coins: CoinData, box: BoxMaps, g: number, shifts: readonly (readonly number[])[]): AffineGenerator[] {
  const lin = box.linear[g] as Int32Array
  const out: AffineGenerator[] = []

  for (const t of shifts) {
    const map = Int32Array.from({ length: box.cells }, (_, x) => translate(box, lin[x] as number, t))

    for (const c of [1, -1]) out.push({ name: `${g}+${t.join('')}${c < 0 ? 'C' : ''}`, map, lineImage: coins.lineImage[g] as Int8Array, lineSign: coins.lineSign[g] as Int8Array, c })
  }

  return out
}

// how many lift pairs of a two-generated group keep an orientation of the held units
export function orientingLiftPairs(coins: CoinData, box: BoxMaps, held: Uint8Array, G: Subgroup, shifts: readonly (readonly number[])[]): { tried: number; orienting: number } {
  const A = liftsOf(coins, box, G.gens[0] as number, shifts)
  const B = liftsOf(coins, box, G.gens[1] as number, shifts)
  let orienting = 0

  for (const a of A) for (const b of B) orienting += orientUnits(held, [a, b]).ok ? 1 : 0

  return { tried: A.length * B.length, orienting }
}

// the elements with a lift that keeps some orientation alone, and every subgroup inside that set
export function insideSubgroups(coins: CoinData, box: BoxMaps, held: Uint8Array, shifts: readonly (readonly number[])[], limit: number): { O: number[]; subgroups: Subgroup[]; complete: boolean } {
  const table = coins.table
  const n = table.permutations.length
  const inO = new Uint8Array(n)

  for (let g = 0; g < n; g++) {
    for (const lift of liftsOf(coins, box, g, shifts)) {
      if (orientUnits(held, [lift]).ok) {
        inO[g] = 1
        break
      }
    }
  }

  const O = Array.from({ length: n }, (_, g) => g).filter(g => inO[g])
  const inside = (members: readonly number[]): boolean => members.every(m => inO[m] === 1)
  const found = new Map<string, Subgroup>()
  let frontier: Subgroup[] = []

  if (O.length > limit) return { O, subgroups: [], complete: false }

  for (const g of O) {
    const h = closure(table, [g])

    if (!inside(h)) continue

    const key = h.join(',')

    if (!found.has(key)) {
      const entry = { gens: [g], members: h }

      found.set(key, entry)
      frontier.push(entry)
    }
  }

  while (frontier.length > 0) {
    const next: Subgroup[] = []

    for (const H of frontier) {
      const bits = new Uint8Array(n)

      for (const m of H.members) bits[m] = 1

      for (const g of O) {
        if (bits[g]) continue

        const K = closure(table, [...H.gens, g])

        if (!inside(K)) continue

        const key = K.join(',')

        if (!found.has(key)) {
          const entry = { gens: [...H.gens, g], members: K }

          found.set(key, entry)
          next.push(entry)
        }
      }
    }

    frontier = next
  }

  return { O, subgroups: [...found.values()], complete: true }
}

// ---- the covering patterns ----
//
// A 2T-equivariant pattern: the root class k0 of r0 streams toward the hub classes S0 (a subset of L' / 2 D4, given as
// class keys), and the class g k0 toward g S0 for g in 2T. 2T acts on the 12 root classes transitively (the Hurwitz
// units act freely on the roots) with stabilizer {+-1}, which fixes every class mod 2 D4, so S is well defined. A
// dock of root class k stores, for each c in S(k), the line of r(k) - c. Covering (every L' class a hub) needs 0 in
// some S(k) and a norm-4 class in some S(k'); since 2T permutes the three norm-4 classes transitively, S0 = {0, n}
// already covers all four, with two lines per root dock. Returned: the held units on the side-4 box about hub 0.

const mod2Key = (c: readonly number[]): number => c.reduce((s, v, k) => s + ((((v % 2) + 2) % 2) << k), 0)

export function coveringPattern(coins: CoinData, box: BoxMaps, twoT: readonly number[], start: readonly number[]): Uint8Array {
  const roots = rootsD4()
  const classOfVector = (v: readonly number[]): number => mod2Key(d4Coordinates([...v]))
  const lineOfClass = new Int8Array(16).fill(-1)
  const rootOfClass: number[][] = Array.from({ length: 16 }, () => [])

  roots.forEach((r, d) => {
    lineOfClass[classOfVector(r)] = LINE_OF[d] as number
    rootOfClass[classOfVector(r)] = r as number[]
  })

  const act = (g: number, v: readonly number[]): number[] => (coins.doubled[g] as number[][]).map(row => row.reduce((s, x, k) => s + x * (v[k] as number), 0) / 2)
  const norm4 = NORM4.map(v => classOfVector(v))
  const representative = (c: number): number[] => (c === 0 ? [0, 0, 0, 0] : ([...(NORM4[norm4.indexOf(c)] as number[])] as number[]))
  const S: number[][] = Array.from({ length: 16 }, () => [])

  for (const g of twoT) {
    const k = classOfVector(act(g, roots[0] as number[]))
    const image = start.map(c => (c === 0 ? 0 : classOfVector(act(g, representative(c))))).sort((a, b) => a - b)

    if ((S[k] as number[]).length === 0) S[k] = image
    else if ((S[k] as number[]).join(',') !== image.join(',')) throw new Error('the pattern is not 2T-equivariant')
  }

  const held = new Uint8Array(box.cells * 12)

  for (let x = 0; x < box.cells; x++) {
    const k = mod2Key(box.coords[x] as number[])
    const r = rootOfClass[k] as number[]

    if (r.length === 0) continue

    for (const c of S[k] as number[]) {
      const rep = representative(c)

      held[x * 12 + (lineOfClass[classOfVector(r.map((v, i) => v - (rep[i] as number)))] as number)] = 1
    }
  }

  return held
}

export const NORM4_KEYS = (): number[] => NORM4.map(v => mod2Key(d4Coordinates([...v])))

export { forces as forcesScalarsAndShear }
