// Breadth-first ball and word-metric distance on a lattice generated by integer step
// vectors (a Cayley graph of Z^d with the given generators). Cells are integer points
// keyed by their coordinates, the ball is every point reachable within R steps, and
// the word metric is the fewest generator steps between two points. Used to read the
// volume growth and metric of a root lattice (e.g. the D4 root system) directly off
// its generators, with no precomputed indexed mesh.

import { add } from '@/code/algebra/vector'

const key = (p: number[]): string => p.join(',')

// The BFS ball of radius R from the origin under the generator steps. Returns the
// step distance of every reached point, the list of points, and the generators used.
export function latticeBall(input: {
  generators: number[][]
  radius: number
  origin?: number[]
}): {
  dist: Map<string, number>
  cells: number[][]
  generators: number[][]
} {
  const { generators, radius } = input
  const origin = input.origin ?? generators[0]!.map(() => 0)
  const dist = new Map<string, number>([[key(origin), 0]])
  const cells: number[][] = [origin]

  let frontier = [origin]

  for (let r = 1; r <= radius; r++) {
    const next: number[][] = []

    for (const p of frontier) {
      for (const g of generators) {
        const q = add(p, g)
        const k = key(q)

        if (!dist.has(k)) {
          dist.set(k, r)
          cells.push(q)
          next.push(q)
        }
      }
    }

    frontier = next
  }

  return { dist, cells, generators }
}

// The word-metric distance between two lattice points by local BFS, capped at `cap`
// steps (returns cap + 1 if not reached within the cap).
export function latticeWordDistance(input: {
  a: number[]
  b: number[]
  generators: number[][]
  cap: number
}): number {
  const { a, b, generators, cap } = input

  if (key(a) === key(b)) {
    return 0
  }

  const seen = new Set([key(a)])

  let frontier = [a]

  for (let r = 1; r <= cap; r++) {
    const next: number[][] = []

    for (const p of frontier) {
      for (const g of generators) {
        const q = add(p, g)
        const k = key(q)

        if (k === key(b)) {
          return r
        }

        if (!seen.has(k)) {
          seen.add(k)
          next.push(q)
        }
      }
    }

    frontier = next
  }

  return cap + 1
}
