// Generic finite-group utilities over any element type: the subgroup generated by a set
// (closure), the commutator subgroup, and membership. Used to decide whether a central
// extension is split or not, the question of whether a spinor double cover is genuine. If the
// central minus-one lies in the commutator subgroup, the cover is NONSPLIT and the projective
// spinor is real, it cannot be relabeled away as a linear representation.

export interface GroupOps<T> {
  multiply(left: T, right: T): T
  inverse(value: T): T
  key(value: T): string
}

// The subgroup generated by the given elements, by closing under the operation.
export function closure<T>(generators: T[], ops: GroupOps<T>): T[] {
  const seen = new Map<string, T>()
  const queue: T[] = []
  const add = (value: T): void => {
    const id = ops.key(value)
    if (!seen.has(id)) {
      seen.set(id, value)
      queue.push(value)
    }
  }
  for (const generator of generators) {
    add(generator)
  }
  for (let index = 0; index < queue.length; index++) {
    for (const generator of generators) {
      add(ops.multiply(queue[index]!, generator))
    }
  }
  return [...seen.values()]
}

// The commutator subgroup, generated by all [a, b] = a b a^-1 b^-1.
export function commutatorSubgroup<T>(
  elements: T[],
  ops: GroupOps<T>,
): T[] {
  const commutators: T[] = []
  for (const a of elements) {
    for (const b of elements) {
      commutators.push(
        ops.multiply(
          ops.multiply(a, b),
          ops.multiply(ops.inverse(a), ops.inverse(b)),
        ),
      )
    }
  }
  return closure(commutators, ops)
}

export function contains<T>(
  elements: T[],
  target: T,
  ops: GroupOps<T>,
): boolean {
  const id = ops.key(target)
  return elements.some(element => ops.key(element) === id)
}
