// Margenstern's STRONGLY universal cellular automaton in the dodecagrid {5,3,4} (hyperbolic 3D), FIVE states
// (arXiv:2104.01561). Rules are 14-char words [current][12 face-neighbours][new] over {W,B,R,G,Y}, rotation
// invariant under the dodecahedron's rotation group (order 60). NOTE, unlike the planar automata, these 3D
// rules are NOT a clean function of the 12-neighbour snapshot alone (one collision exists, rules 4 vs 118),
// because the construction also uses shadowed-face / phase context the snapshot does not carry, so the table is
// compiled with keep-first and the collision is reported. See land/text/papers/more-5/2104.01561.pdf and the
// shared engine in margenstern-ca.ts. Rotation handling for the full 60-element dodecahedral group is a further
// step; the rules themselves are loaded here verbatim.
import { compileMargensternCa, cyclicRotations } from '@/code/compute/margenstern-ca'

export const DODECAGRID_RULES: string[] = [
  'WWWWWWWWWWWWWW', 'WBWWWWWWWWWWWW', 'WRWWWWWWWWWWWW', 'WGWWWWWWWWWWWW', 'WYWWWWWWWWWWWW', 'WBBWWWWWWWWWWW', 'WGGWWWWWWWWWWW', 'WRRWWWWWWWWWWW', 'WYYWWWWWWWWWWW', 'WRBWWWWWWWWWWW',
    'WRYWWWWWWWWWWW', 'WGBWWWWWWWWWWW', 'WGRWWWWWWWWWWW', 'WGYWWWWWWWWWWW', 'WYBWWWWWWWWWWW', 'WBBBWWWWWWWWWW', 'WRRRWWWWWWWWWW', 'WGGGWWWWWWWWWW', 'WYYYWWWWWWWWWW', 'WBBRWWWWWWWWWW',
    'WBBGWWWWWWWWWW', 'WBBYWWWWWWWWWW', 'WRRBWWWWWWWWWW', 'WRRGWWWWWWWWWW', 'WRRYWWWWWWWWWW', 'WGGBWWWWWWWWWW', 'WGGRWWWWWWWWWW', 'WGGYWWWWWWWWWW', 'WYYBWWWWWWWWWW', 'WYYRWWWWWWWWWW',
    'WYYGWWWWWWWWWW', 'WBRGWWWWWWWWWW', 'WBRYWWWWWWWWWW', 'WBGRWWWWWWWWWW', 'WBGYWWWWWWWWWW', 'WBYRWWWWWWWWWW', 'WBYGWWWWWWWWWW', 'WRGYWWWWWWWWWW', 'WRYGWWWWWWWWWW', 'BWWWWWWWWWWWWB',
    'BBWWWWWWWWWWWB', 'WWWWWWWBWWBBWW', 'WWWWWWBBWWBBWB', 'WWWWWWRBWWBBWB', 'BWWWWWWBWWBBWW', 'WWWBWWWBWWBBWW', 'RWWWWWWWWWWWWR', 'BRWWWWWWWWWWWB', 'WWBWWWWBWWBBWB', 'WWWWRWWBWWBBWW',
    'WWWWRWBBWWBBWB', 'WWWWRWWBBWBBWB', 'BWWWRWWBWWBBWW', 'WWWBRWWBWWBBWW', 'WBWWWWWBWWBBWW', 'WBWWWWBBWWBBWW', 'WWWBWWBBWWBBWB', 'BWWBWWWBWWBBWW', 'WWWWWWWBWWBBBW', 'BWWWWWWBWWBBBB',
    'WWWWWWBBWWBBBB', 'BWWWWWBBWWBBBW', 'BBBWWWWWWWWWWB', 'WWWWWWWBRWBBWW', 'WWWWWWBBRWBBWW', 'WWWWWWWBBBBWRW', 'WWWBWWWBBBBWRB', 'BWWWWWWBBBBWRW', 'WWWWWBBBBBBWRW', 'WRYWBWWWBWBWWW',
    'WRYWBWWWBWWWWW', 'BRYBBWWWBWWWWB', 'WRYWBWBWBWWWWB', 'BRYWBWWWBWWWWW', 'WRYBBWWWBWWWWW', 'WRYWBWBWBWBWWB', 'WRYBBWWWBWBWWW', 'WRYWBWRWBWWWWR', 'RRYWBWWWBWWWWW', 'WRYRBWWWBWWWWW',
    'WRYWBWRWBWBWWR', 'WRYRBWWWBWBWWW', 'RWBWWBRBWWBWWR', 'RBBWWBRBWWBWWR', 'RBBRWBRBWWWWWR', 'RWBRWBBBWWWWWB', 'BWBRWBRBWWWWWR', 'RWBBWBRBWWWWWR', 'RWBRWBRBWWWWWR', 'BWBWWBRBWWBWWR',
    'RWBWWBBBWWBWWB', 'RWBBWBRBWWBWWR', 'YBWWWBYBWWRWRY', 'YBWYWBYBWWWWWY', 'YBBWWBYBWWRWRY', 'YBBYWBYBWWWWWY', 'YBWYWBRBWWWWWR', 'RBWYWBYBWWWWWY', 'YBWRWBYBWWWWWY', 'YBWWWBRBWWRWRR',
    'RBWWWBYBWWRWRY', 'YBWRWBYBWWRWRY', 'BYRBBWWWBWBWWB', 'BYRBBWBWBWWWWB', 'BYRBBWRWBWBWWR', 'RYRBBWWWBWBWWB', 'BYRRBWWWBWBWWB', 'BYRBBWRWBWWWWR', 'RYRBBWBWBWWWWB', 'BYRRBWBWBWWWWB',
    'BRYGBWBWBWWWWB', 'RBBRWBGBWWWWWR', 'YBBYWBGBWWWWWY', 'BYRGBWBWBWWWWB', 'GGGWWWBWWWWWWG', 'GGGRWWWWWWWWWG', 'GGGYWWWWWWWWWG', 'WGWWWWWWWWWWWB', 'GGGBBWBWBBBBBB', 'GGGRWBBBWBBBBR',
    'GGGYWBBBWBBBBY', 'BGBBWWWWWWWWWG', 'BGBWWWWWWWWWWB', 'BGWWWWWWWWWWWW', 'RBBRWBRBWWWWWR', 'YBBYWBWBWWWWWY', 'YBBYWBYBWWWWWY', 'BYRWBWBWBWWWWB', 'WWWWWWWYWWYYWW', 'WWWWWRWYWWYYWR',
    'RWWWWWWYWWYYWW', 'WWWRWWWYWWYYWW', 'WWWWWWYYWWYRWW', 'WWWWWWRYWWYRWR', 'WWWRWWYYWWYRWR', 'WWWWBWYYWWYRWW', 'WWWWWWRRWWRYWW', 'WWWWWBRRWWRYWB', 'BWWWWWRRWWRYWW', 'WWWBWWRRWWRYWW',
    'WWWWWWWRBWRRWW', 'WWWWWWBRBWRRWR', 'RWWWWWWRBWRRWW', 'WWWBWWWRBWRRWW', 'WRYBBWRWBWWWWG', 'WRYGBWWWBWWWWW', 'BRYBBWGWBWWWWB', 'GRYBBWWWBWWWWG', 'GRRBBWWWBBBBBB', 'WRRBBWWWBWWWWW',
    'WRRWBWWWBWWWWW', 'WRRWBWWWBWBWWW', 'YBGYWBYBWWWWWR', 'RBGYWBYBWWWWWY', 'YBBRWBYBWWWWWY', 'RGBRWBRBWWWWWR', 'BRRBBWBWBWWWWB', 'BRRBBWWWBWBWWB', 'WRYGBWWWBWBWWW', 'WRRBBWWWBWBWWW',
    'WRYBBWRWBWBWWG', 'GRYBBWWWBWBWWG', 'GRRBBWWBBBBBBB', 'BRYBBWWWBWBWWB', 'WWWGWWWYWWYYWW', 'YBGWWBYBWWRWRR', 'RBGWWBYBWWRWRY', 'YBBWWBYBWWRWRY', 'YBBRWBYBWWRWRY', 'RGBWWBRBWWBWWR',
    'RBBWWBRBWWBWWR', 'BRYBBWGWBWBWWB', 'WWWBWRWYWWYYWG', 'GWWBWWWYWWYYWG', 'GWWBBWWYWBYYBW', 'WWWBWWWYWWYYWW', 'WWWWWGWWWYYWYB', 'BWWWWGWWWYYWYW', 'WWWWWBWWWYYWYW', 'WWGWWWYYWWYRWW',
    'WGWWWWRRWWRYWW', 'WWWGWWWBWWBBWW', 'WWWGWWWRBWRRWW', 'WWWWWWBYWWYYWB', 'BWWWWWWYWWYYWW', 'WBWWWWRRWWRYWW', 'WWBWWWYYWWYRWW', 'WWWWWBWWWYYWYW', 'BRYWBWWWBWBWWW', 'WBYWBWWWBWBWWW',
    'WRYBBWBWBWWWWY', 'YRYBBWWWBWWWWY', 'WRYYBWWWBWWWWW', 'BRYBBWYWBWWWWR', 'RYBRWBRBWWWWWB', 'RRYBBWYWBWWWWW', 'YBYRBWWWBWWWWW', 'BRYBBWRWBWWWWB', 'WBYWBWWWBWWWWW', 'YBYYWBYBWWWWWY',
    'BYBBBWBWBWWWWB', 'BYBRWBRBWWWWWR', 'RRBBWBRBWWWWWR', 'BYBBBWWWBWBWWB', 'WWWWWWBRWWRYWB', 'BWWWWWRRWWRYWW', 'WWWBWWRRWWRYWW', 'WBWWWWWYWWYYWW', 'WWBBWWWRBWRRWW', 'WRYYBWWWBWBWWW',
    'WRYBBWBWBWBWWY', 'YRYBBWWWBWBWWY', 'RYBWWBRBWWBWWB', 'BYBWWBRBWWBWWR', 'YBYRBWWWBWBWWW', 'WWWYWWWYWWYYWW', 'YBYWWBYBWWRWRY', 'WWWBWWBYWWYYWY', 'YWWBWWWYWWYYWY', 'BRYBBWYWBWBWWR',
    'YBWRWWWYWWYYWW', 'RRYBBWYWBWBWWW', 'WYWWWWRRWWRYWB', 'BYWWWWRRWWRYWW', 'WWYWWWYYWWYRWW', 'RRBBWBRBWWBWWR', 'WWWWWYWWWYYWYW', 'WWWYWWWRBWRRWW', 'BYRGBWRWBWWWWW', 'RBWRWBRBWWWWWW',
    'YWBYWBYBWWWWWW', 'WYRBBWBWBWWWWW', 'BYRGBWWWBWWWWW', 'RBWWWBGBWWWWWW', 'YWBWWBGBWWWWWW', 'WBWRWBRBWWWWWW', 'WWBYWBYBWWWWWW', 'BWWBBWBWBWWWWW', 'WWWWWBWBWBWWWW', 'WYRGBWWWBWWWWW',
    'GGGWWWWWWWWWWW', 'GGGBBWWWBBBBBW', 'WBWWWBRBWWWWWW', 'WWBWWBYBWWWWWW', 'WWWRWBWBWWWWWW', 'WWWYWBWBWWWWWW', 'WWWWBWWWBWWWWW', 'BWWGBWWWBWWWWW', 'WBWWWBGBWWWWWW', 'GGWWWBBBWBBBBW',
    'GWGWWBBBWBBBBW', 'WGGBBWWWBBBBBW', 'GGBWWWWWWWWWWW', 'WWWBBWWWBBBBBW', 'BGGWWWWWWWWWWW', 'WWWGBWWWBWWWWW', 'GWWBBWWWBBBBBW', 'WGWWWBBBWBBBBW', 'WWGWWBBBWBBBBW', 'WWWWBWWWBBBBBW',
    'GBBWWWWWWWWWWW'
]

// rotation handling uses a simple 12-cyclic placeholder (the true dodecahedral group is order 60); the rules
// are stored verbatim and the snapshot collision is tolerated and counted.
export const dodecagrid5State = compileMargensternCa({
  name: 'dodecagrid-5-state',
  rules: DODECAGRID_RULES,
  neighbourLen: 12,
  rotate: cyclicRotations(12),
  onConflict: 'keep-first',
})
