// Margenstern's weakly universal cellular automaton on the pentagrid {5,4}, THREE states (arXiv:1510.09129).
// Rules are 12-char words [current][5 edge-neighbours][5 vertex-neighbours][new] over {W,B,R}, rotation
// invariant under the 5-fold rotation (which shifts the edge ring and the vertex ring together). See
// land/text/papers/more-5/1510.09129.pdf and the shared engine in margenstern-ca.ts.
import { compileMargensternCa, doubleRingRotations } from '@/code/compute/margenstern-ca'

export const PENTAGRID_3STATE_RULES: string[] = [
  'WWWWWWWWWWWW', 'BWWWWWWWWWWB', 'RWWWWWWWWWWR', 'WBWWWWWWWWWW', 'WRWWWWWWWWWW', 'BBWWWWWWWWWB', 'BRWWWWWWWWWB', 'RBWWWWWWWWWR', 'RRWWWWWWWWWR', 'WWWWWWBWWWWW', 'WWWWWWRWWWWW', 'BWWWWWBWWWWB', 'BWWWWWRWWWWB', 'RWWWWWBWWWWR',
    'RWWWWWRWWWWR', 'WWWWWBWBWWWW', 'WWBWBWBBBWWW', 'WWBWRBBWWBBR', 'WWWWWBRBWWWW', 'RWBWWBBWWBBW', 'WRWWWBWBWWWW', 'WRBWWBBWWWWW', 'WWBWWWWRWWWW', 'BWBWWBWWWWWB', 'WBWWWWWBWWWW', 'WBWWWWBWWWWW', 'BBWBWWWWRWWB', 'BBRBWWWWWWWB',
    'BBWWWWWRWWWB', 'WWBWBWBBWWWW', 'WWWWWWBBWWWW', 'WRBWWBBWWBBW', 'WWBWWBBWWWWW', 'BBWBWWWRWWWB', 'WRBWBWBBWWWR', 'BWBWWWWRWWWB', 'RWBWRBBWWBBR', 'WRWWWBRBWWWW', 'RRBWWBBWWBBW', 'BRWWWWWRWWWB', 'BBRBWWWWRWWB', 'BBRBWWWRWWWB',
    'RRBWBWBBWWWR', 'BRBWWWWRWWWB', 'WRWWWWBBWWWW', 'WBWWWWWRWWWW', 'WWBWWBWBBBWW', 'WWBWWWBWWWWW', 'WWWBWBBBWWWW', 'WWBRWBWBBBWR', 'RWBWWBWBBBWW', 'WWBWWWBRWWWW', 'WRBWWBWBBBWW', 'WRBWWWBWWWWW', 'WWBWWBWBWWWW', 'WRWBWBBBWWWR',
    'RWBRWBWBBBWR', 'RRBWWBWBBBWW', 'WRBWWWBRWWWW', 'WRBWWBWBWWWW', 'BWRWWWWRWWWB', 'RBWBWWWWBWBW', 'BRBWWWWWWWWB', 'WBWBWWWRBWBW', 'WWRBWBBBWWWW', 'WBWBWWWWBWBW', 'WBWBWWRWBWBW', 'WBRBWWWWBWBW', 'RWWBWBBBWWWW', 'WBWBWRWWBWBR',
    'RBWWBWWWBWBW', 'WRWBWBWBBWWW', 'WBWWBWWRBWBW', 'WBWWBWWWBWBW', 'WBWWBWRWBWBW', 'WBWWBRWWBWBW', 'WBRWBWWWBWBR', 'RWWBWBWBBWWW', 'RBRBWWWWBWBW', 'RRWBWBBBWWWR', 'WBWBWRRWBWBR', 'WBRBWWWRBWBW', 'RWRBWBBBWWWW', 'RBWBWRWWBWBR',
    'RBRWBWWWBWBR', 'RRWBWBWBBWWW', 'WBWWBRRWBWBW', 'RBWWBRWWBWBW', 'WBRWBWWRBWBR', 'WWBWBWBBWBWW', 'WRBWBWBBWBWR', 'RWBWBWBBWBWW', 'BBWWWWWWWWRB', 'WWBRBWBBWBWW', 'WWBWBWBBRBWW', 'BBWWWWWWWRWB', 'BBWRWWWWWWWB', 'WBWBWRWBWWBR',
    'BBWWBWWWWRWB', 'BBWRBWWWWWWB', 'BBWWBWWWRWWB', 'BBRWBWWWWWWB', 'BBWWBWWRWWWB', 'RRBWBWBBWBWR', 'RWBRBWBBWBWW', 'BBWWRWWWWWRB', 'WWBRBWBBRBWW', 'BBWRWWWWRWWB', 'WBWBWRRBWWBR', 'BBWRBWWWWRWB', 'BBWWRWWWWRWB', 'BBWRBWWWRWWB',
    'BBRWBWWWRWWB', 'RBRWBWWBBWBR', 'RBWWBRWBBWBW', 'WBWWBRRBBWBW', 'WWBRWBWBRBWR', 'RWBRWBWBWBWR', 'WWBWBWBBBWBW', 'WWBWWWBBWWWW', 'WWBWWBWBBWWW', 'WRBWBWBBBWBR', 'WWBWWBRBBBWW', 'RWBWBWBBBWBW', 'BRWWWBWWWWWB', 'WWBRBWBBBWBW',
    'BWWWWBWRWWWB', 'RWBWWBWBBWWW', 'WRBWWWWBWWWW', 'WRWWWWBWWWWW', 'WRBWWBWBBWWW', 'WWBWBRBBBWBR', 'WWBWWBBRWBBW', 'RRBWBWBBBWBR', 'WRBWWBRBBBWW', 'RWBRBWBBBWBW', 'BRWWWBWRWWWB', 'WRBWWWBBWWWW', 'RRBWWBWBBWWW', 'RWBWBRBBBWBR',
    'WRBWWBBRWBBW', 'BRWWWBRWWWWB', 'WWBWBBWBBWBW', 'WWWBWBBBBWWW', 'WWBRWBBWBBWR', 'BWBWWBWWWBWB', 'WBWWWBWBWWWW', 'WBBWWWBWWWWW', 'BWWWWBBWWWWB', 'BWBWBWWBWWRB', 'BBBWWWWWWWWB', 'WBWWWWBBWWWW', 'WWBWBBRBBWBW', 'WWRBWBBBBWWR',
    'RWBWWBBWBBWW', 'BWBWBRWBWWWB', 'WRBWBBWBBWBR', 'RWWBWBBBBWWW', 'WRBWWBBWBBWW', 'BWBWWBWRWBWB', 'BWBWBWRBWWWB', 'RWBWBBWBBWBR', 'WRWBWBBBBWWW', 'WWBWWBBRBBWW', 'BRBWWBWWWBWW', 'BRWWWBBWWWWB', 'BRBWBWWBWWWB', 'BBBWWWWRWWWB',
    'RWWRBBWBBWBW', 'WRBWWBRWWBWB', 'RRBWBWBWBWWR', 'BRWWWBBRWWWB', 'WWBRBBWBBWBW', 'WWBWWBBWBBWW', 'BWBWWBRWWBWB', 'BWWWWBBRWWWB', 'BWBWBWWBWWWB', 'WBWWWBRBBBWW', 'BWRWWBWBWWWB', 'RBBWWWWWWWWR', 'WRWWWWWBWWWW', 'WWBWBBWBBWWW',
    'BWWWWBWWBRBB', 'WBBWWRWWWWWW', 'WBRWWBBWWWWW', 'BWBBWBRWWWWB', 'BWWWWWWWWBRB', 'WBWWWBWWWWWW', 'WWBRWWWWWWWW', 'BWWBWRBWWWWB', 'WBWWWWRBWWWW', 'BWWWWBRWBRBB', 'BRBBWBWWWWWB', 'WBWRWBRBBBWR', 'WWBWBBRBBWWW', 'BRWWWBWWBRBR',
    'BWBBWBWRWWWB', 'BWRWWWWWWBRB', 'WBWWWBWRWWWW', 'RBWWWBRBRBWW', 'BRRWWBWBWWWB', 'RBBWWWWRWWWR', 'WRBWBRWBBWWW', 'WRRWWBWWBBWW', 'RWWWWBWRBRBB', 'WRBWWRWWWWWW', 'WRRWWBBWWWWW', 'BWWWWWWRWBRB', 'BRWBWRBWWWWB', 'WBWWRBRBBBWW',
    'BWBBWBWWWWWB', 'BRWWWWWWWBRB', 'WWBRWWWRWWWW', 'BWWBWRBRWWWB', 'WBWWWBRBBBRW', 'BWRBWRBWWWWB', 'BWWBWRBWRWWB', 'WBRWWWWBBWWW', 'BRBBWBRWWWWB', 'BRWWWBRWBRBB', 'BRBBWBWRWWWB', 'RBWRWBRBBBWW', 'WRBWBBRBBWWR', 'RRBWWBWWBBWW',
    'BRWWWBWRBRBB', 'WRBWBWBRWWWW', 'BWRWWWWRWBRR', 'WBRWWBRBBRWW', 'BWRWWBRBWWWB', 'RWBWBBWBBWWW', 'BRWWWWBWWWWB', 'WWBWWRWRBBWW', 'BWRWWBWWBRBB', 'WWBWWWRWWWWW', 'WBBWWRWRWWWW', 'WWRWBWBWWWWW', 'RWWWWWWWWBRB', 'WWWWWWBRWWWW',
    'WWRRWWWWWWWW', 'WWBRBBWBBWWW', 'WWBWBWBWWWWW', 'WBWWWWWBBWWW', 'WWBWBWBRWWWW', 'WRBWBWBWWWWR', 'BRWBWWWWWWWB', 'WBWWBWBRBWWW', 'WRBWRBWBBBWW', 'RWBWBWBWWWWW', 'BWWBWWRRWWWB', 'WBRWBWBWBWWR', 'WWBWWBWBBBRW', 'WWBWBRBWWWWW',
    'BWWWRBWWWRWB', 'WBWWWRRWWWWW', 'RBRWWWBWWWWR', 'RRWWWWWBWWWR', 'WRWWWWWRWWWW', 'WWRWWWWRWWWW', 'BWBWWBWWRRWB', 'WBRWWRWBWWWW', 'WBRWWWBWWWWW', 'WWBWWWBWWWBW', 'WWBWWWBRWWBW', 'BRWWRBWWWRWB', 'WBWBWWWRWBBW', 'BWBWWBWRRRWB',
    'WRBWWWBWWWBW', 'BWWWRBRWWRWB', 'BRBWWBWWRRWB', 'BWBWWBRWRRWB', 'WRWBWWWBWBBW', 'RWWWRBWWWRWR', 'WRWBWWWWWBBW', 'WRWWWRRWWWWW', 'RRRWWWBWWWWR', 'RRWWWWWRWWWR', 'WWBWBWBRBWWW', 'BWRWWBWWRRWB', 'WBRWWRWRWWWW', 'WWBWWWRWWWBW',
    'WRWBRWWBWBBW', 'WWBWWWRRWWBW', 'WBWBWWRBWBBW', 'BWRWRBWWWRWR', 'WBWWWRRRWWWW', 'WWBWWRBWWWBW', 'WRWBRWWWWBBR', 'WWWBWWWRRWWW', 'WRWBWWRBWBBW', 'RWRWRBWWWRWB', 'RRWBWWWWWBBW', 'WRWWWRRRWWWW', 'WWRBWWWRWWWW', 'WWBWWRRWWWBW',
    'WWRWWBWBWWWW', 'WWWBWBRBBBWW', 'RWBRBWWWWWWR', 'BRWWWWRWWBWB', 'RRWWWWBBWWWR', 'BRWWBWWRWWWB', 'WBWWWBWWBWWW', 'WBBWBWWWBWWW', 'WBRWWWWRWWWW', 'BWWWWBWBWWWB', 'WWWWWWWRBWWW', 'WWRWWBWWBBWW', 'WWBWWBWRBBWW', 'WWRWWBRBWWWW',
    'WWRBWBRBBBWR', 'WRRWWBWBWWWW', 'RWWBWBRBBBWW', 'RWBRBWWRWRWB', 'BRRWWWRWWBWR', 'WBWWWBWRBWWW', 'WWBWWBWRWWWW', 'WWWBRRBBBBWW', 'RWBWBWRBBWWW', 'BWRRBWWWWRWB', 'RBWWWWRWRBWB', 'RBWWWRBRWWWR', 'BBRWBWWRWWWB', 'WRRWWBWWBWWW',
    'WRBWBWWWBWWR', 'WRRWWWWBWWWW', 'WBRWWWWBWWWW', 'BBWWRWRWWBWB', 'RBWWWWBBWWWR', 'WBWWWBRWBWWW', 'RBBWBWWWBWWW', 'WRBWWWWBRWWW', 'BRWWWBWBWWWB', 'BBWWWWRWWBWB', 'WWBWWBRBWWWW', 'BWBRBWWRWRWB', 'BBRWWWRWWBWB', 'BBWWWWRWRBWB',
    'WBRWWBWWBWWW', 'RBWWWRBBWWWR', 'BBRWBWWRWWRB', 'RBRWWWWBWWWR', 'WBWWWWBRWWWW', 'BWBRBWWWWRRB', 'BBRWBRWRWWWB', 'WWBWWBWBRWWW', 'BWBRBRWWWRWR', 'BBRWBWRRWWWB', 'RWBRBWWWWRWR', 'RRWWWRBBWWWR', 'BRRWBWWRWWWB', 'RBRWWWWRWWWR',
    'WBBRBWWWBWWW', 'BWWWWBRBWWWB'
]

export const pentagrid3State = compileMargensternCa({
  name: 'pentagrid-3-state',
  rules: PENTAGRID_3STATE_RULES,
  neighbourLen: 10,
  rotate: doubleRingRotations(5),
})
