// The unified hyperbolic tessellation generator.
//
// Builds a renderer-agnostic Scene (see ../scene.ts) of a regular hyperbolic tessellation from its Schlafli
// symbol, by the Coxeter reflection method: take one cell, reflect it across its mirror walls, and the whole
// infinite structure unfolds. Ported and generalized from the three.js mesh generator that drove the
// clue.surf /vibe/mesh page. The original was hardcoded for 3D honeycombs {p,q,r}. This version reads the
// dimension from the symbol via mirrorFrame, so the SAME code builds 2D tilings ({7,3}, rank 3) and 3D
// honeycombs ({5,3,4}, rank 4).
//
// It handles tessellations whose CELL is finite (spherical), which covers the compact honeycombs and the 2D
// tilings (the polygon cell is always finite). Cells are grown nearest-first from the origin so the result is
// a uniform ball of cells rather than a lumpy frontier. Paracompact honeycombs with ideal cells (the Coxeter
// BFS plus Lorentz-boost path in the original) are a later addition.

import { mirrorFrame, classifyGeometry } from '@/code/substrate/coxeter/schlafli'
import {
  hnormalize, toBall, reflect, hyperbolicDistance, reflectionMatrix,
  identityMatrix, mulMatrix, applyMatrix, matrixKey, nullVector, spatialAxes,
} from '@/code/render/geometry/minkowski'
import type { Scene, SceneEdge } from '@/code/render/scene'

const DEFAULT_MAX_CELLS = 12000
const MAX_VERTICES_PER_CELL = 500
const MAX_STABILIZER_ELEMENTS = 5000
const BOUNDARY_CLIP = 0.9996

export type HoneycombOptions = {
  // the Schlafli symbol, e.g. [7,3] (a 2D tiling) or [5,3,4] (a 3D honeycomb)
  symbol: number[]
  // how many cells to enumerate, more means denser detail toward the boundary
  maxCells?: number
}

// build the tessellation Scene for a Schlafli symbol
export function buildHoneycombScene(input: HoneycombOptions): Scene {
  const { symbol, maxCells = DEFAULT_MAX_CELLS } = input
  const { normals, metric, timeAxis } = mirrorFrame(symbol)
  const dim = normals.length // the rank (number of mirrors), = symbol.length + 1
  const ballDim = spatialAxes(dim, timeAxis).length // 2 for a tiling, 3 for a honeycomb

  // the cell stabilizer is generated by every mirror except the LAST, which is the wall we step across to the
  // next cell. The fundamental vertex is fixed by every mirror except the FIRST.
  const stabilizerNormals = normals.slice(0, dim - 1)
  const faceNormal = normals[dim - 1]!

  // the fundamental cell vertex (the meet of all mirrors but the first)
  const v0 = hnormalize(nullVector(normals.slice(1), metric), metric, timeAxis)
  const baseVertices = orbitVertices(v0, stabilizerNormals, metric)
  const baseEdges = polyhedronEdges(baseVertices, metric)

  // the cell center (the meet of the stabilizer mirrors), used to order cells by distance from the origin
  const cellCenter = hnormalize(nullVector(stabilizerNormals, metric), metric, timeAxis)

  const faceReflections = generateFaceReflections(stabilizerNormals, faceNormal, metric, dim)
  const cellTransforms = enumerateCells(faceReflections, cellCenter, timeAxis, dim, maxCells)

  // replicate the cell edges across every cell, deduplicated in ball space
  const edges: SceneEdge[] = []
  const seen = new Set<string>()
  for (const transform of cellTransforms) {
    const ballVerts = baseVertices.map((v) => toBall(applyMatrix(transform, v, dim), timeAxis))
    for (const [i, j] of baseEdges) {
      const a = ballVerts[i]!
      const b = ballVerts[j]!
      if (norm(a) > BOUNDARY_CLIP || norm(b) > BOUNDARY_CLIP) continue
      const key = pairKey(a, b)
      if (seen.has(key)) continue
      seen.add(key)
      edges.push({ a, b })
    }
  }

  return { dim: ballDim, symbol: symbol.slice(), edges, cellCount: cellTransforms.length }
}

// is the cell (the symbol minus its last entry) a finite spherical polytope? finite cells are the case this
// generator handles. for a 2D tiling the cell is a single polygon, always finite.
export function hasFiniteCell(symbol: number[]): boolean {
  const cell = symbol.slice(0, -1)
  if (cell.length <= 1) return true
  return classifyGeometry(cell) === 'spherical'
}

// the Euclidean norm of a ball point
function norm(v: number[]): number {
  let s = 0
  for (const x of v) s += x * x
  return Math.sqrt(s)
}

// the orbit of the fundamental vertex under the cell stabilizer (reflecting across the stabilizer mirrors)
function orbitVertices(v0: number[], stabilizerNormals: number[][], metric: number[]): number[][] {
  const vertices: number[][] = [v0]
  const visited = new Set<string>([vkey(v0)])
  const queue: number[][] = [v0]
  while (queue.length > 0 && vertices.length < MAX_VERTICES_PER_CELL) {
    const v = queue.shift()!
    for (const n of stabilizerNormals) {
      const vr = reflect(v, n, metric)
      const k = vkey(vr)
      if (visited.has(k)) continue
      visited.add(k)
      vertices.push(vr)
      queue.push(vr)
    }
  }
  return vertices
}

// the edges of a cell, the vertex pairs at the minimum (edge) hyperbolic distance
function polyhedronEdges(vertices: number[][], metric: number[]): [number, number][] {
  let minDist = Infinity
  const cap = Math.min(vertices.length, 20)
  for (let i = 0; i < cap; i++) for (let j = i + 1; j < cap; j++) {
    const d = hyperbolicDistance(vertices[i]!, vertices[j]!, metric)
    if (d > 0.01 && d < minDist) minDist = d
  }
  const edgeLength = minDist < Infinity ? minDist : 1
  const tolerance = edgeLength * 1.2
  const edges: [number, number][] = []
  for (let i = 0; i < vertices.length; i++) for (let j = i + 1; j < vertices.length; j++) {
    const d = hyperbolicDistance(vertices[i]!, vertices[j]!, metric)
    if (d > 0.01 && d < tolerance) edges.push([i, j])
  }
  return edges
}

// every face reflection of a cell, found by conjugating the stepping mirror by the finite cell stabilizer
// group. these are the walls we reflect across to reach neighbouring cells.
function generateFaceReflections(stabilizerNormals: number[][], faceNormal: number[], metric: number[], dim: number): number[][] {
  const stab = stabilizerNormals.map((n) => reflectionMatrix(n, metric))
  const faceRefl = reflectionMatrix(faceNormal, metric)
  const I = identityMatrix(dim)

  // enumerate the (finite) cell stabilizer group, tracking each element's inverse for conjugation. reflections
  // are involutions, so the inverse of S*g is g_inverse*S.
  const elements: { mat: number[]; inv: number[] }[] = [{ mat: I, inv: I }]
  const visited = new Set<string>([matrixKey(I)])
  const queue: { mat: number[]; inv: number[] }[] = [{ mat: I, inv: I }]
  while (queue.length > 0 && elements.length < MAX_STABILIZER_ELEMENTS) {
    const { mat: g, inv: gInv } = queue.shift()!
    for (const S of stab) {
      const H = mulMatrix(S, g, dim)
      const HInv = mulMatrix(gInv, S, dim)
      const k = matrixKey(H)
      if (visited.has(k)) continue
      visited.add(k)
      elements.push({ mat: H, inv: HInv })
      queue.push({ mat: H, inv: HInv })
    }
  }

  const faces: number[][] = []
  const seen = new Set<string>()
  for (const { mat: g, inv: gInv } of elements) {
    const gDgInv = mulMatrix(mulMatrix(g, faceRefl, dim), gInv, dim)
    const k = matrixKey(gDgInv)
    if (seen.has(k)) continue
    seen.add(k)
    faces.push(gDgInv)
  }
  return faces
}

// enumerate cell transforms nearest-first (a min-heap on the ball radius of the cell center), so a capped
// count yields a uniform ball of cells instead of a lumpy frontier
function enumerateCells(faceReflections: number[][], cellCenter: number[], timeAxis: number, dim: number, maxCells: number): number[][] {
  const radiusOf = (m: number[]): number => norm(toBall(applyMatrix(m, cellCenter, dim), timeAxis))

  const heap: { mat: number[]; r: number }[] = []
  const push = (item: { mat: number[]; r: number }): void => {
    heap.push(item)
    let i = heap.length - 1
    while (i > 0) {
      const parent = (i - 1) >> 1
      if (heap[parent]!.r <= heap[i]!.r) break
      const t = heap[parent]!; heap[parent] = heap[i]!; heap[i] = t
      i = parent
    }
  }
  const pop = (): { mat: number[]; r: number } => {
    const top = heap[0]!
    const last = heap.pop()!
    if (heap.length > 0) {
      heap[0] = last
      let i = 0
      const n = heap.length
      for (;;) {
        const l = 2 * i + 1, rr = 2 * i + 2
        let smallest = i
        if (l < n && heap[l]!.r < heap[smallest]!.r) smallest = l
        if (rr < n && heap[rr]!.r < heap[smallest]!.r) smallest = rr
        if (smallest === i) break
        const t = heap[smallest]!; heap[smallest] = heap[i]!; heap[i] = t
        i = smallest
      }
    }
    return top
  }

  const transforms: number[][] = []
  const visited = new Set<string>()
  const I = identityMatrix(dim)
  visited.add(matrixKey(I))
  push({ mat: I, r: radiusOf(I) })
  while (heap.length > 0 && transforms.length < maxCells) {
    const { mat } = pop()
    transforms.push(mat)
    for (const F of faceReflections) {
      const H = mulMatrix(F, mat, dim)
      const k = matrixKey(H)
      if (visited.has(k)) continue
      visited.add(k)
      push({ mat: H, r: radiusOf(H) })
    }
  }
  return transforms
}

function vkey(v: number[]): string {
  return v.map((x) => Math.round(x * 1e5)).join(',')
}

function pairKey(a: number[], b: number[]): string {
  const ka = a.map((x) => Math.round(x * 1e4)).join(',')
  const kb = b.map((x) => Math.round(x * 1e4)).join(',')
  return ka < kb ? `${ka}|${kb}` : `${kb}|${ka}`
}
