// Dimension-general Minkowski geometry for hyperbolic honeycombs and tilings.
//
// This is the renderer-agnostic math core, ported and generalized from the three.js mesh generator that
// drove the clue.surf /vibe/mesh page (mesh/site/clue.surf/home/site/tool/honeycomb/mesh-generator.ts). The
// original hardcoded the 4-vector signature (+,+,+,-) for 3D honeycombs {p,q,r}. Here everything takes an
// explicit METRIC (an array of +1/-1 per axis) and a TIME AXIS, so the same code builds 2D tilings {p,q}
// (rank 3) and 3D honeycombs {p,q,r} (rank 4) and higher. No three.js, no DOM, no react. Plain number
// arrays, so it runs in node, the browser, or a worker.
//
// Coordinate model: points live on the hyperboloid hdot(p,p) = -1 in R^{n,1} (the time axis is the -1 axis).
// `toBall` projects to the Poincare ball (the spatial axes), giving a point with norm < 1 that any renderer
// can draw. A regular honeycomb is generated by reflecting one cell across its mirror walls (a Coxeter
// reflection group), so the whole infinite structure comes from a tiny seed.

// the Minkowski inner product under a diagonal metric (each entry +1 spacelike or -1 timelike)
export function hdot(a: number[], b: number[], metric: number[]): number {
  let s = 0
  for (let i = 0; i < a.length; i++) s += metric[i]! * a[i]! * b[i]!
  return s
}

// the spatial axes (every axis except the timelike one), in order, used for the ball projection
export function spatialAxes(dim: number, timeAxis: number): number[] {
  const out: number[] = []
  for (let i = 0; i < dim; i++) if (i !== timeAxis) out.push(i)
  return out
}

// normalize a hyperboloid point to the unit hyperboloid hdot(p,p) = -1. For timelike points this is a
// straight rescale. For spacelike / lightlike directions (ideal or ultra-ideal vertices, which a paracompact
// honeycomb can produce) it truncates to a finite point a fixed hyperbolic distance out along the spatial
// direction, so the renderer always gets a usable in-ball point.
export function hnormalize(p: number[], metric: number[], timeAxis: number): number[] {
  const sq = -hdot(p, p, metric) // positive for timelike points
  if (sq > 1e-10) {
    // keep the point on the UPPER sheet (positive timelike component), so the ball projection is well-defined
    const sign = p[timeAxis]! < 0 ? -1 : 1
    const norm = sign * Math.sqrt(sq)
    return p.map((x) => x / norm)
  }
  const sx = spatialAxes(p.length, timeAxis)
  let spatialSq = 0
  for (const a of sx) spatialSq += p[a]! * p[a]!
  if (spatialSq < 1e-10) { const v = new Array<number>(p.length).fill(0); v[timeAxis] = 1; return v }
  const spatialNorm = Math.sqrt(spatialSq)
  const truncDist = 1.2
  const sinhD = Math.sinh(truncDist)
  const coshD = Math.cosh(truncDist)
  const out = new Array<number>(p.length).fill(0)
  for (const a of sx) out[a] = (sinhD * p[a]!) / spatialNorm
  out[timeAxis] = coshD
  return out
}

// project a hyperboloid point to the Poincare ball, returning only the spatial coordinates (length dim-1),
// which is a point of norm < 1 ready to render (a 2D disk point for a tiling, a 3D ball point for a honeycomb)
export function toBall(p: number[], timeAxis: number): number[] {
  const denom = 1 + p[timeAxis]!
  const sx = spatialAxes(p.length, timeAxis)
  if (denom < 0.001) return sx.map(() => 0)
  return sx.map((a) => p[a]! / denom)
}

// reflect a point across the mirror hyperplane with unit normal n (Minkowski reflection)
export function reflect(p: number[], n: number[], metric: number[]): number[] {
  const nn = hdot(n, n, metric)
  if (Math.abs(nn) < 1e-10) return p.slice()
  const f = (2 * hdot(p, n, metric)) / nn
  return p.map((x, i) => x - f * n[i]!)
}

// the hyperbolic distance between two hyperboloid points
export function hyperbolicDistance(a: number[], b: number[], metric: number[]): number {
  return Math.acosh(Math.max(1, -hdot(a, b, metric)))
}

// the reflection as a dim x dim matrix (column-major, like the original generator) so cell transforms can be
// composed by matrix multiplication. m[j*dim+i] is row i, column j.
export function reflectionMatrix(n: number[], metric: number[]): number[] {
  const dim = n.length
  const nn = hdot(n, n, metric)
  const f = 2 / nn
  const m = new Array<number>(dim * dim).fill(0)
  for (let i = 0; i < dim; i++) {
    for (let j = 0; j < dim; j++) {
      const delta = i === j ? 1 : 0
      m[j * dim + i] = delta - f * n[i]! * n[j]! * metric[j]!
    }
  }
  return m
}

// the identity dim x dim matrix (column-major)
export function identityMatrix(dim: number): number[] {
  const m = new Array<number>(dim * dim).fill(0)
  for (let i = 0; i < dim; i++) m[i * dim + i] = 1
  return m
}

// multiply two dim x dim column-major matrices
export function mulMatrix(a: number[], b: number[], dim: number): number[] {
  const out = new Array<number>(dim * dim).fill(0)
  for (let i = 0; i < dim; i++) {
    for (let j = 0; j < dim; j++) {
      let sum = 0
      for (let k = 0; k < dim; k++) sum += a[k * dim + i]! * b[j * dim + k]!
      out[j * dim + i] = sum
    }
  }
  return out
}

// apply a dim x dim column-major matrix to a vector
export function applyMatrix(m: number[], v: number[], dim: number): number[] {
  const out = new Array<number>(dim).fill(0)
  for (let i = 0; i < dim; i++) {
    let sum = 0
    for (let j = 0; j < dim; j++) sum += m[j * dim + i]! * v[j]!
    out[i] = sum
  }
  return out
}

// a rounded key for deduplicating matrices (cells) by their numeric content
export function matrixKey(m: number[]): string {
  return m.map((v) => Math.round(v * 1e5)).join(',')
}

// the determinant of a small square matrix (cofactor expansion, fine for the dim 2 and 3 minors used here)
function det(m: number[][]): number {
  const n = m.length
  if (n === 1) return m[0]![0]!
  if (n === 2) return m[0]![0]! * m[1]![1]! - m[0]![1]! * m[1]![0]!
  let s = 0
  for (let c = 0; c < n; c++) {
    const minor = m.slice(1).map((row) => row.filter((_, k) => k !== c))
    s += (c % 2 === 0 ? 1 : -1) * m[0]![c]! * det(minor)
  }
  return s
}

// solve for the vector v perpendicular (in the Minkowski metric) to every given normal, i.e. hdot(v, n) = 0
// for each n in `normals`. With dim-1 normals in dim-space this is the generalized cross product (cofactor
// expansion), which always returns a valid null vector regardless of which component happens to be zero, so
// it is robust to the timelike axis sitting anywhere in the metric (mirrorFrame's eigenbasis can place it at
// any index). Used to find a cell center or a fundamental vertex (the meet of several mirrors).
export function nullVector(normals: number[][], metric: number[]): number[] {
  const dim = metric.length
  // each equation hdot(v, n) = sum metric[k]*v[k]*n[k] = 0 becomes a row [metric[k]*n[k]]
  const M = normals.map((n) => n.map((nk, k) => metric[k]! * nk))
  const v = new Array<number>(dim).fill(0)
  for (let i = 0; i < dim; i++) {
    const minor = M.map((row) => row.filter((_, k) => k !== i))
    v[i] = (i % 2 === 0 ? 1 : -1) * det(minor)
  }
  return v
}
