// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/tiling": {
    params: {};
  };
  "/honeycomb": {
    params: {};
  };
  "/rooms": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/tiling" | "/honeycomb" | "/rooms";
  };
  "./page/page.tsx": {
    id: "page/page";
    page: "/";
  };
  "./page/tiling/page.tsx": {
    id: "page/tiling/page";
    page: "/tiling";
  };
  "./page/honeycomb/page.tsx": {
    id: "page/honeycomb/page";
    page: "/honeycomb";
  };
  "./page/rooms/page.tsx": {
    id: "page/rooms/page";
    page: "/rooms";
  };
};

type RouteModules = {
  "root": typeof import(".//root.tsx");
  "page/page": typeof import(".//./page/page.tsx");
  "page/tiling/page": typeof import(".//./page/tiling/page.tsx");
  "page/honeycomb/page": typeof import(".//./page/honeycomb/page.tsx");
  "page/rooms/page": typeof import(".//./page/rooms/page.tsx");
};