// Conformance for code/algebra/group/finite-group: the generic closure, commutator
// subgroup, and membership utilities. Checked on two concrete groups whose structure
// is known independently:
//   - the cyclic group Z/6 (abelian): closure of a generator is the cyclic subgroup it
//     generates (size 6/gcd), and the commutator subgroup is trivial.
//   - SL(2,2) = S3 (non-abelian, order 6): its commutator subgroup is A3 of order 3.

import { suite, check, equal, ok, notOk } from '@/test/code/harness'
import {
  closure,
  commutatorSubgroup,
  contains,
  type GroupOps,
} from '@/code/algebra/group/finite-group'
import {
  specialLinear,
  multiplyModP,
  type MatrixModP,
} from '@/code/algebra/group/special-linear'

// Z/6 under addition.
const cyclic: GroupOps<number> = {
  multiply: (a, b) => (a + b) % 6,
  inverse: a => (6 - a) % 6,
  key: a => String(a),
}

// SL(2,2) = GL(2,2) = S3 under matrix multiplication over F2.
const reduce2 = (v: number): number => ((v % 2) + 2) % 2
const matOps: GroupOps<MatrixModP> = {
  multiply: (a, b) => multiplyModP(a, b, 2),
  // over F2, -1 = 1, so the det-1 inverse [d,-b,-c,a] is [d,b,c,a]
  inverse: a =>
    [a[3], a[1], a[2], a[0]].map(reduce2) as unknown as MatrixModP,
  key: a => a.join(','),
}

suite('algebra/group/finite-group: closure over Z/6', [
  check('closure of {1} is all of Z/6 (order 6)', () => {
    equal(closure([1], cyclic).length, 6, '<1> = Z/6')
  }),
  check('closure of {2} is {0,2,4} (order 3 = 6/gcd(2,6))', () => {
    const sub = new Set(closure([2], cyclic).map(x => cyclic.key(x)))

    equal(sub.size, 3, '|<2>| = 3')
    ok(
      [0, 2, 4].every(x => sub.has(String(x))),
      '<2> = {0,2,4}',
    )
    notOk(sub.has('1'), '1 is not in <2>')
  }),
  check('closure of {3} is {0,3} (order 2)', () => {
    equal(closure([3], cyclic).length, 2, '|<3>| = 2')
  }),
  check('closure of {0} is the trivial subgroup', () => {
    equal(closure([0], cyclic).length, 1, '|<0>| = 1')
  }),
  check('commutator subgroup of an abelian group is trivial', () => {
    const all = [0, 1, 2, 3, 4, 5]

    equal(commutatorSubgroup(all, cyclic).length, 1, "Z/6' = {0}")
  }),
  check('contains tracks membership', () => {
    const sub = closure([2], cyclic)

    ok(contains(sub, 4, cyclic), '4 is in <2>')
    notOk(contains(sub, 5, cyclic), '5 is not in <2>')
  }),
])

suite(
  'algebra/group/finite-group: closure and commutator over S3 = SL(2,2)',
  [
    check(
      'closing the SL(2,2) elements reproduces the group (order 6)',
      () => {
        const group = specialLinear(2)

        equal(closure(group, matOps).length, 6, '|SL(2,2)| = 6')
      },
    ),
    check(
      'SL(2,2) is generated by a transvection and a swap (order 6)',
      () => {
        // [[1,1],[0,1]] (order 3) and [[0,1],[1,0]] (order 2) generate S3
        const generators: MatrixModP[] = [
          [1, 1, 0, 1],
          [0, 1, 1, 0],
        ]

        equal(
          closure(generators, matOps).length,
          6,
          'two generators give all 6',
        )
      },
    ),
    check('commutator subgroup of S3 is A3 (order 3)', () => {
      const group = specialLinear(2)

      equal(commutatorSubgroup(group, matOps).length, 3, "S3' = A3")
    }),
    check(
      'the commutator subgroup is normal and contained in the group',
      () => {
        const group = specialLinear(2)
        const derived = commutatorSubgroup(group, matOps)

        for (const d of derived) {
          ok(
            contains(group, d, matOps),
            'derived element lies in the group',
          )
        }
      },
    ),
  ],
)
