// A lattice gas on the hyperbolic {3,4,3,4} honeycomb needs more than the cell graph. The committed
// rule collides the 24 slots of a cell through a table keyed by slot labels, and streams slot d of a
// cell into slot d of the neighbour across facet d, so every cell needs its 24 facets LABELLED by the
// 24 D4 roots, with two conditions: inside a cell the labels are an isometry of the facet directions
// onto the roots (so the collision sees a genuine 24-cell coin, and opposite labels are antipodal
// facets), and across every shared facet the two labels are d and -d (so a tone that leaves through
// facet d enters the neighbour through its facet -d and keeps moving toward its facet d, a straight
// chain of antipodal crossings, and streaming is a bijection).
//
// The labels come from a FRAME per cell, a group element g with g * c0 the cell's center, the label of
// a facet read in the base cell after pulling it back by g. Stepping across the facet labelled d moves
// the frame by a fixed transport tau_d = F_d X_d, the face reflection F_d followed by an element X_d of
// the cell stabilizer. The labels are consistent exactly when every closed walk of steps returns the
// frame it started with (no holonomy). Two transports are built here:
//
// - antipodal: X_d = Z, the point inversion of the base cell (minus one on the 24-cell, central in its
//   symmetry group [3,4,3]). Sending the outer generator to Z is a homomorphism from [3,4,3,4] onto
//   [3,4,3] that fixes [3,4,3] (Z commutes with the three mirrors it must, and (r3 Z)^4 = r3^4 = 1
//   because the last Coxeter label is 4, even), so its kernel is a torsion-free group acting simply
//   transitively on the cells, generated by the tau_d. Its Cayley graph IS the cell graph, and the
//   labels close around every loop. On the flat {3,4,3,3} the same map fails ((r3 Z)^3 = -r3), which is
//   why the flat mesh uses translations instead.
// - translation: X_d = R_d, the reflection of the base cell in its facet direction d, so tau_d is the
//   product of two mirrors perpendicular to d, the hyperbolic analogue of the translation that labels
//   the flat D4 mesh. Around a ridge four cells meet where the flat honeycomb puts three, so this
//   transport carries holonomy and cannot label the honeycomb: the control that the antipodal closure
//   is a fact about the group and not about the check.
//
// The antipodal transport is not a translation: relative to parallel transport it turns a frame by
// minus the mirror in the step direction, orientation reversing, so neighbouring cells see the coin
// with opposite handedness. Stated wherever it is used.

import {
  coxeterCellFrame,
  type CoxeterCellFrame,
} from '@/code/substrate/coxeter/frame'
import {
  type Mat,
  type Vec,
  innerJ,
  matMul,
  matVec,
  identity,
  reflectionMatrix,
  pointKey,
  toPoincare,
  nullVector,
} from '@/code/substrate/coxeter/minkowski'
import { rootsD4 } from '@/code/algebra/group/root-system'
import { Mesh } from '@/code/tool/mesh'

export type TransportKind = 'antipodal' | 'translation'

export type LabelledCoin = {
  readonly frame: CoxeterCellFrame
  // faceOfLabel[k] is the face (index into frame.faces) carrying the D4 root rootsD4()[k]
  readonly faceOfLabel: number[]
  // the opposite label of each label, the negated root
  readonly opposite: number[]
  // the largest deviation of the scaled facet-direction Gram matrix from the D4 root Gram matrix
  readonly gramError: number
  // the point inversion of the base cell, and whether it lies in the cell stabilizer
  readonly inversion: Mat
  readonly inversionInStabilizer: boolean
  readonly stabilizerOrder: number
  // Z F_d Z = F_{-d} for every label, the inversion exchanging antipodal facets
  readonly inversionExchangesAntipodes: boolean
  // the base cell's facet directions, one per label, in the c0-orthogonal space
  readonly directions: Vec[]
}

function reflectionThroughCentre(input: {
  direction: Vec
  metric: number[]
}): Mat {
  const { direction, metric } = input
  const norm = Math.sqrt(innerJ(direction, direction, metric))

  return reflectionMatrix(
    direction.map(v => v / norm),
    metric,
  )
}

function maxAbsDifference(a: Mat, b: Mat): number {
  let worst = 0

  for (let i = 0; i < a.length; i++) {
    for (let j = 0; j < a.length; j++) {
      worst = Math.max(
        worst,
        Math.abs((a[i]?.[j] ?? 0) - (b[i]?.[j] ?? 0)),
      )
    }
  }

  return worst
}

// The labelled 24-cell coin of {3,4,3,4}: each facet of the base cell matched to a D4 root by an
// isometry of the facet directions, found by a deterministic depth-first search over four basis roots.
export function labelledCoin(): LabelledCoin {
  const frame = coxeterCellFrame([3, 4, 3, 4])
  const { faces, center, metric, normals, dim } = frame
  const c0c0 = innerJ(center, center, metric)

  // the facet directions: the step to each neighbour's center, projected off c0
  const directions = faces.map(face => {
    const step = matVec(face, center).map(
      (v, a) => v - (center[a] ?? 0),
    )
    const along = innerJ(step, center, metric) / c0c0

    return step.map((v, a) => v - along * (center[a] ?? 0))
  })
  const scale = 2 / innerJ(directions[0]!, directions[0]!, metric)
  const gram = directions.map(a =>
    directions.map(b => scale * innerJ(a, b, metric)),
  )

  const roots = rootsD4()
  const dot = (a: number[], b: number[]): number =>
    a.reduce((s, v, i) => s + v * (b[i] ?? 0), 0)
  const opposite = roots.map(root =>
    roots.findIndex(other =>
      other.every((v, i) => v === -(root[i] ?? 0)),
    ),
  )
  // four independent roots, (1,1,0,0), (1,-1,0,0), (0,0,1,1), (0,0,1,-1)
  const basisRoots = [
    [1, 1, 0, 0],
    [1, -1, 0, 0],
    [0, 0, 1, 1],
    [0, 0, 1, -1],
  ]
  const basis = basisRoots.map(b =>
    roots.findIndex(r => r.every((v, i) => v === b[i])),
  )
  // every root in that basis: r = sum_i c_i b_i, the basis is orthogonal with norm 2
  const coefficients = roots.map(r =>
    basisRoots.map(b => dot(r, b) / 2),
  )

  let faceOfLabel: number[] = []
  let gramError = Number.POSITIVE_INFINITY

  const chosen: number[] = []

  const complete = (): boolean => {
    const map: number[] = []

    for (let k = 0; k < roots.length; k++) {
      const c = coefficients[k]!
      const target = directions[0]!.map((_, a) =>
        chosen.reduce(
          (s, face, i) =>
            s + (c[i] ?? 0) * (directions[face]?.[a] ?? 0),
          0,
        ),
      )
      const match = directions.findIndex(
        d =>
          d.reduce((s, v, a) => s + Math.abs(v - (target[a] ?? 0)), 0) <
          1e-6,
      )

      if (match < 0 || map.includes(match)) {
        return false
      }

      map.push(match)
    }

    faceOfLabel = map

    return true
  }

  const search = (depth: number): boolean => {
    if (depth === basis.length) {
      return complete()
    }

    for (let face = 0; face < faces.length; face++) {
      if (chosen.includes(face)) {
        continue
      }

      const fits = chosen.every(
        (other, i) =>
          Math.abs(
            (gram[face]?.[other] ?? 0) -
              dot(roots[basis[depth]!]!, roots[basis[i]!]!),
          ) < 1e-6,
      )

      if (!fits || Math.abs((gram[face]?.[face] ?? 0) - 2) > 1e-6) {
        continue
      }

      chosen.push(face)

      if (search(depth + 1)) {
        return true
      }

      chosen.pop()
    }

    return false
  }

  if (search(0)) {
    gramError = 0

    for (let k = 0; k < roots.length; k++) {
      for (let l = 0; l < roots.length; l++) {
        const g = gram[faceOfLabel[k]!]?.[faceOfLabel[l]!] ?? 0

        gramError = Math.max(
          gramError,
          Math.abs(g - dot(roots[k]!, roots[l]!)),
        )
      }
    }
  }

  // the cell stabilizer, by BFS over the four cell mirrors, keyed by the rounded matrix
  const mirrors = normals
    .slice(0, 4)
    .map(normal => reflectionMatrix(normal, metric))
  const stabilizer: Mat[] = [identity(dim)]
  const seen = new Set<string>([pointKey(stabilizer[0]!.flat())])

  // a for-of over a growing array visits the elements pushed during the loop, a breadth-first closure
  for (const element of stabilizer) {
    for (const mirror of mirrors) {
      const g = matMul(mirror, element)
      const key = pointKey(g.flat())

      if (!seen.has(key)) {
        seen.add(key)
        stabilizer.push(g)
      }
    }
  }

  // Z x = -x + 2 <x, c0> / <c0, c0> c0
  const inversion: Mat = Array.from({ length: dim }, (_, a) =>
    Array.from(
      { length: dim },
      (_, b) =>
        (a === b ? -1 : 0) +
        (2 * (center[a] ?? 0) * (metric[b] ?? 1) * (center[b] ?? 0)) /
          c0c0,
    ),
  )
  const inversionExchangesAntipodes = faceOfLabel.every((face, k) => {
    const conjugate = matMul(matMul(inversion, faces[face]!), inversion)

    return (
      maxAbsDifference(conjugate, faces[faceOfLabel[opposite[k]!]!]!) <
      1e-9
    )
  })

  return {
    frame,
    faceOfLabel,
    opposite,
    gramError,
    inversion,
    inversionInStabilizer: seen.has(pointKey(inversion.flat())),
    stabilizerOrder: stabilizer.length,
    inversionExchangesAntipodes,
    directions: faceOfLabel.map(face => directions[face]!),
  }
}

// The frame step across the facet labelled k, tau_k = F_k X_k.
export function labelTransports(input: {
  coin: LabelledCoin
  kind: TransportKind
}): Mat[] {
  const { coin, kind } = input
  const { faces, metric } = coin.frame

  return coin.faceOfLabel.map((face, k) => {
    const second =
      kind === 'antipodal'
        ? coin.inversion
        : reflectionThroughCentre({
            direction: coin.directions[k]!,
            metric,
          })

    return matMul(faces[face]!, second)
  })
}

export type HyperbolicBall = {
  // the lattice-gas mesh: `cells` real cells, then one phantom cell standing for everything outside the
  // ball, which every outward facet of the last shell points at
  readonly mesh: Mesh
  readonly cells: number
  readonly phantom: number
  readonly distance: Int32Array
  readonly frames: Mat[]
  readonly keys: string[]
  // cell index by key
  readonly index: Map<string, number>
  // the largest entry-wise disagreement between a cell's stored frame and the frame the transport
  // gives on reaching it along another path, relative to the largest entry of the frame
  readonly frameMismatch: number
  // how many (cell, label) steps land back on a cell whose stored frame disagrees beyond 1e-6
  readonly inconsistentSteps: number
  // neighbour(neighbour(c, k), -k) = c on every step inside the ball
  readonly returnsExactly: boolean
}

function relativeMismatch(a: Mat, b: Mat): number {
  let scale = 1

  for (const row of a) {
    for (const v of row) {
      scale = Math.max(scale, Math.abs(v))
    }
  }

  return maxAbsDifference(a, b) / scale
}

// The ball of cells within `radius` facet steps of the base cell, labelled by the given transport.
export function buildHyperbolicBall(input: {
  coin: LabelledCoin
  radius: number
  kind?: TransportKind
}): HyperbolicBall {
  const { coin, radius } = input
  const kind = input.kind ?? 'antipodal'
  const transports = labelTransports({ coin, kind })
  const { center, timeAxis } = coin.frame
  const degree = transports.length
  const keyOf = (g: Mat): string =>
    pointKey(toPoincare(matVec(g, center), timeAxis))
  const frames: Mat[] = [identity(coin.frame.dim)]
  const keys: string[] = [keyOf(frames[0]!)]
  const index = new Map<string, number>([[keys[0]!, 0]])
  const distance: number[] = [0]
  const links: number[][] = []

  let frameMismatch = 0
  let inconsistentSteps = 0

  for (let head = 0; head < frames.length; head++) {
    const g = frames[head]!
    const row = new Array<number>(degree).fill(-1)

    for (let k = 0; k < degree; k++) {
      const next = matMul(g, transports[k]!)
      const key = keyOf(next)

      let id = index.get(key)

      if (id === undefined && (distance[head] ?? 0) < radius) {
        id = frames.length
        index.set(key, id)
        frames.push(next)
        keys.push(key)
        distance.push((distance[head] ?? 0) + 1)
      } else if (id !== undefined) {
        const mismatch = relativeMismatch(frames[id]!, next)

        frameMismatch = Math.max(frameMismatch, mismatch)

        if (mismatch > 1e-6) {
          inconsistentSteps++
        }
      }

      row[k] = id ?? -1
    }

    links.push(row)
  }

  const cells = frames.length
  const phantom = cells
  const table = new Int32Array((cells + 1) * degree)

  for (let c = 0; c < cells; c++) {
    for (let k = 0; k < degree; k++) {
      const n = links[c]?.[k] ?? -1

      table[c * degree + k] = n < 0 ? phantom : n
    }
  }

  for (let k = 0; k < degree; k++) {
    table[phantom * degree + k] = phantom
  }

  let returnsExactly = true

  for (let c = 0; c < cells; c++) {
    for (let k = 0; k < degree; k++) {
      const n = table[c * degree + k] ?? phantom

      if (
        n !== phantom &&
        table[n * degree + (coin.opposite[k] ?? 0)] !== c
      ) {
        returnsExactly = false
      }
    }
  }

  const opposite = coin.opposite

  return {
    mesh: {
      id: `hyperbolic-3434-ball-${radius}-${kind}`,
      degree,
      cellCount: cells + 1,
      neighbour(cell, direction) {
        return table[cell * degree + direction] ?? phantom
      },
      opposite(direction) {
        return opposite[direction] ?? direction
      },
    },
    cells,
    phantom,
    distance: Int32Array.from(distance),
    frames,
    keys,
    index,
    frameMismatch,
    inconsistentSteps,
    returnsExactly,
  }
}

// The ideal vertex of the base cell fixed by the last four mirrors, and the cells that touch it: the
// cusp layer, whose centers lie on one horosphere. Each is found by the vertex test (the cell's frame
// pulls the vertex back onto a vertex of the base cell), and its SKIN distance is the breadth-first
// distance inside the layer, from the base cell, over facets shared by two layer cells.
export type CuspLayer = {
  // skin distance by cell key
  readonly skin: Map<string, number>
  // every layer cell found, in breadth-first order, with its frame
  readonly members: { key: string; skin: number; frame: Mat }[]
  // the Busemann level <center, vertex> of every layer cell, which must be one value
  readonly levelSpread: number
  // how many layer neighbours a layer cell has, over the cells whose layer neighbourhood is complete
  readonly layerDegree: number[]
}

export function cuspLayer(input: {
  coin: LabelledCoin
  skinRadius: number
}): CuspLayer {
  const { coin, skinRadius } = input
  const { normals, metric, center, timeAxis, dim } = coin.frame
  const transports = labelTransports({ coin, kind: 'antipodal' })
  const vertex = nullVector(normals.slice(1), metric)

  const unit = (v: Vec): Vec => {
    const t = v[timeAxis] ?? 1

    return v.map(x => x / t)
  }

  const inverse = (g: Mat): Mat =>
    Array.from({ length: dim }, (_, a) =>
      Array.from(
        { length: dim },
        (_, b) =>
          (metric[a] ?? 1) * (g[b]?.[a] ?? 0) * (metric[b] ?? 1),
      ),
    )
  // the 24 vertices of the base cell, the orbit of the vertex under its four cell mirrors. A cell with
  // frame g touches the vertex exactly when g^-1 v is one of them.
  const mirrors = normals
    .slice(0, 4)
    .map(normal => reflectionMatrix(normal, metric))
  const baseVertices = new Set<string>([pointKey(unit(vertex))])
  const queue: Vec[] = [unit(vertex)]

  for (const point of queue) {
    for (const mirror of mirrors) {
      const image = unit(matVec(mirror, point))
      const key = pointKey(image)

      if (!baseVertices.has(key)) {
        baseVertices.add(key)
        queue.push(image)
      }
    }
  }

  const touches = (g: Mat): boolean =>
    baseVertices.has(pointKey(unit(matVec(inverse(g), vertex))))
  const keyOf = (g: Mat): string =>
    pointKey(toPoincare(matVec(g, center), timeAxis))
  const frames: Mat[] = [identity(dim)]
  const skin = new Map<string, number>([[keyOf(frames[0]!), 0]])
  const layerDegree: number[] = []
  const levels: number[] = [innerJ(center, vertex, metric)]

  for (const g of frames) {
    const here = skin.get(keyOf(g)) ?? 0

    let degree = 0

    for (const tau of transports) {
      const next = matMul(g, tau)

      if (!touches(next)) {
        continue
      }

      degree++

      const key = keyOf(next)

      if (!skin.has(key) && here < skinRadius) {
        skin.set(key, here + 1)
        frames.push(next)
        levels.push(innerJ(matVec(next, center), vertex, metric))
      }
    }

    if (here < skinRadius) {
      layerDegree.push(degree)
    }
  }

  return {
    skin,
    members: frames.map(frame => {
      const key = keyOf(frame)

      return { key, skin: skin.get(key) ?? 0, frame }
    }),
    levelSpread: Math.max(...levels) - Math.min(...levels),
    layerDegree,
  }
}

// The exact cell-graph distance from the base cell to the cell with frame `target`, when it is at most
// near.radius + far.radius: the meet of the ball around the base cell and the ball around the target
// (the far ball's frames carried over by the target frame), minimized over shared cells. Undefined
// when the two balls do not meet, which proves the distance exceeds the sum of the radii.
export function bulkDistance(input: {
  near: HyperbolicBall
  far: HyperbolicBall
  target: Mat
  coin: LabelledCoin
}): number | undefined {
  const { near, far, target, coin } = input
  const { center, timeAxis } = coin.frame
  const index = near.index

  let best: number | undefined

  far.frames.forEach((frame, i) => {
    const key = pointKey(
      toPoincare(matVec(matMul(target, frame), center), timeAxis),
    )
    const hit = index.get(key)

    if (hit !== undefined) {
      const total = (near.distance[hit] ?? 0) + (far.distance[i] ?? 0)

      best = best === undefined ? total : Math.min(best, total)
    }
  })

  return best
}
