// Stabilizer quantum-code algebra over GF(2), for small codes. A Pauli on n qubits is a pair of
// bitmasks (x, z): bit q of x is an X on qubit q, bit q of z a Z. This is the symplectic
// representation: weight, commutation, the stabilizer group, the logical operators, and the code
// distance all follow from bit operations on (x, z). The holographic HaPPY-code experiment verifies
// the [[5,1,3]] perfect code and its erasure recovery through these.

export type Pauli = {
  x: number
  z: number
}

// The number of set bits in an integer (the qubit count an X or Z mask touches).
export function popcount(value: number): number {
  let v = value
  let n = 0

  while (v) {
    n += v & 1
    v >>>= 1
  }

  return n
}

// The weight of a Pauli: the number of qubits it acts on non-trivially (X, Y, or Z).
export function pauliWeight(p: Pauli): number {
  return popcount(p.x | p.z)
}

// The qubit support of a Pauli as a bitmask: the qubits it touches.
export function pauliSupport(p: Pauli): number {
  return p.x | p.z
}

// Whether two Paulis COMMUTE, by the symplectic inner product over GF(2): they commute iff
// popcount(a.x & b.z) + popcount(a.z & b.x) is even.
export function pauliCommute(a: Pauli, b: Pauli): boolean {
  return (popcount(a.x & b.z) + popcount(a.z & b.x)) % 2 === 0
}

// Encode a Pauli's (x, z) into one integer key (x in the low bits, z shifted by `qubits`), for set
// membership tests of the stabilizer group.
export function pauliKey(p: Pauli, qubits: number): number {
  return p.x | (p.z << qubits)
}

// The stabilizer group (mod phase) generated by `generators` over `qubits` qubits: the GF(2) span,
// returned as a set of pauliKey integers. Has 2^(number of generators) elements.
export function stabilizerGroup(input: {
  generators: readonly Pauli[]
  qubits: number
}): Set<number> {
  const { generators, qubits } = input
  const g = generators.length
  const span = new Set<number>()

  for (let bits = 0; bits < 1 << g; bits++) {
    let x = 0
    let z = 0

    for (let k = 0; k < g; k++) {
      if (bits & (1 << k)) {
        x ^= generators[k]!.x
        z ^= generators[k]!.z
      }
    }

    span.add(x | (z << qubits))
  }

  return span
}

// The non-trivial logical operators of a stabilizer code over `qubits` qubits: every Pauli that
// commutes with all generators (is in the normalizer) but is NOT in the stabilizer group `span`.
// Excludes the identity. Used to read off the code distance and erasure correctability.
export function logicalOperators(input: {
  generators: readonly Pauli[]
  span: Set<number>
  qubits: number
}): Pauli[] {
  const { generators, span, qubits } = input
  const dim = 1 << qubits
  const logicals: Pauli[] = []

  for (let x = 0; x < dim; x++) {
    for (let z = 0; z < dim; z++) {
      if (x === 0 && z === 0) {
        continue
      }

      const p: Pauli = { x, z }

      if (!generators.every(s => pauliCommute(p, s))) {
        continue
      } // not in the normalizer

      if (span.has(x | (z << qubits))) {
        continue
      } // a trivial (stabilizer) logical

      logicals.push(p)
    }
  }

  return logicals
}

// The code distance: the minimum weight over the logical operators. Infinity if there are none.
export function codeDistance(logicals: readonly Pauli[]): number {
  let distance = Infinity

  for (const l of logicals) {
    distance = Math.min(distance, pauliWeight(l))
  }

  return distance
}

// Whether an erasure set (a qubit bitmask) is CORRECTABLE: it is iff no logical operator is supported
// ENTIRELY within the erased qubits. (A logical hidden inside the erasure is unrecoverable.)
export function erasureCorrectable(input: {
  logicals: readonly Pauli[]
  erased: number
}): boolean {
  const { logicals, erased } = input

  return !logicals.some(l => (pauliSupport(l) & ~erased) === 0)
}
