// Lattice gauge theory with a finite subgroup of SU(3) in place of SU(3): every link holds one of a
// finite list of 3 x 3 unitary matrices, stored as its index, and the Wilson action is unchanged,
//
//   S = beta sum over plaquettes of (1 - Re Tr U_p / 3)
//
// A finite group is what a discrete base could carry per link. At strong coupling it reproduces the
// continuous group, and above a freezing coupling the links lock onto the identity because the nearest
// nontrivial element costs a finite action (Creutz, Jacobs and Rebbi 1979, Bhanot and Rebbi 1981).
//
// The group is generated by closure from a few matrices, never typed in element by element, and the
// multiplication table is computed once, so a plaquette is three table lookups.

import { Rng } from '@/code/tool/rng'
import { Hypercubic, makeHypercubic } from '@/code/tool/hypercubic'

// A complex 3 x 3 matrix, entry (i, j) at 2 (3 i + j) (real) and 2 (3 i + j) + 1 (imaginary).
export type Matrix3 = Float64Array

export type FiniteGroup = {
  readonly form: 'finite-group'
  readonly order: number
  readonly matrices: readonly Matrix3[]
  // product[a * order + b] is the index of matrices[a] matrices[b]
  readonly product: Int16Array
  readonly inverse: Int16Array
  readonly identity: number
  // Re Tr of each element
  readonly trace: Float64Array
}

export function multiply3(a: Matrix3, b: Matrix3): Matrix3 {
  const out = new Float64Array(18)

  for (let i = 0; i < 3; i++) {
    for (let j = 0; j < 3; j++) {
      let re = 0
      let im = 0

      for (let k = 0; k < 3; k++) {
        const ar = a[2 * (3 * i + k)] ?? 0
        const ai = a[2 * (3 * i + k) + 1] ?? 0
        const br = b[2 * (3 * k + j)] ?? 0
        const bi = b[2 * (3 * k + j) + 1] ?? 0

        re += ar * br - ai * bi
        im += ar * bi + ai * br
      }

      out[2 * (3 * i + j)] = re
      out[2 * (3 * i + j) + 1] = im
    }
  }

  return out
}

// A matrix from rows of [re, im] pairs.
export function matrix3(rows: readonly (readonly (readonly [number, number])[])[]): Matrix3 {
  const out = new Float64Array(18)

  rows.forEach((row, i) =>
    row.forEach(([re, im], j) => {
      out[2 * (3 * i + j)] = re
      out[2 * (3 * i + j) + 1] = im
    }),
  )

  return out
}

export function determinant3(a: Matrix3): [number, number] {
  const at = (i: number, j: number): [number, number] => [a[2 * (3 * i + j)] ?? 0, a[2 * (3 * i + j) + 1] ?? 0]
  const mul = (x: [number, number], y: [number, number]): [number, number] => [
    x[0] * y[0] - x[1] * y[1],
    x[0] * y[1] + x[1] * y[0],
  ]
  let re = 0
  let im = 0

  for (const [p, sign] of [
    [[0, 1, 2], 1],
    [[1, 2, 0], 1],
    [[2, 0, 1], 1],
    [[0, 2, 1], -1],
    [[2, 1, 0], -1],
    [[1, 0, 2], -1],
  ] as const) {
    const term = mul(mul(at(0, p[0]), at(1, p[1])), at(2, p[2]))

    re += sign * term[0]
    im += sign * term[1]
  }

  return [re, im]
}

// A matrix times the phase that makes its determinant 1 (the principal cube root).
export function toSpecial(a: Matrix3): Matrix3 {
  const [re, im] = determinant3(a)
  const angle = -Math.atan2(im, re) / 3
  const scale = 1 / Math.cbrt(Math.hypot(re, im))
  const c = Math.cos(angle) * scale
  const s = Math.sin(angle) * scale
  const out = new Float64Array(18)

  for (let k = 0; k < 9; k++) {
    const xr = a[2 * k] ?? 0
    const xi = a[2 * k + 1] ?? 0

    out[2 * k] = xr * c - xi * s
    out[2 * k + 1] = xr * s + xi * c
  }

  return out
}

function keyOf(a: Matrix3): string {
  return Array.from(a, x => {
    const rounded = Math.round(x * 1e6)

    return rounded === 0 ? 0 : rounded
  }).join(',')
}

// The closure of the generators under multiplication. Throws past limit elements, so an infinite
// group (a generator of irrational angle) is refused rather than run forever.
export function generateGroup(input: { generators: readonly Matrix3[]; limit?: number }): FiniteGroup {
  const { generators, limit = 4000 } = input
  const identity = matrix3([
    [[1, 0], [0, 0], [0, 0]],
    [[0, 0], [1, 0], [0, 0]],
    [[0, 0], [0, 0], [1, 0]],
  ])
  const matrices: Matrix3[] = [identity]
  const index = new Map<string, number>([[keyOf(identity), 0]])

  for (let next = 0; next < matrices.length; next++) {
    const element = matrices[next] ?? identity

    for (const generator of generators) {
      const candidate = multiply3(element, generator)
      const key = keyOf(candidate)

      if (!index.has(key)) {
        if (matrices.length >= limit) {
          throw new Error(`group closure passed ${limit} elements`)
        }

        index.set(key, matrices.length)
        matrices.push(candidate)
      }
    }
  }

  const order = matrices.length
  const product = new Int16Array(order * order)
  const inverse = new Int16Array(order)

  for (let a = 0; a < order; a++) {
    for (let b = 0; b < order; b++) {
      const found = index.get(keyOf(multiply3(matrices[a] ?? identity, matrices[b] ?? identity)))

      if (found === undefined) {
        throw new Error('a product left the group, so the closure is not a group')
      }

      product[a * order + b] = found

      if (found === 0) {
        inverse[a] = b
      }
    }
  }

  const trace = Float64Array.from(matrices, m => (m[0] ?? 0) + (m[8] ?? 0) + (m[16] ?? 0))

  return { form: 'finite-group', order, matrices, product, inverse, identity: 0, trace }
}

// The size of the center: elements commuting with every generator's image, i.e. with every element.
export function centerOrder(group: FiniteGroup): number {
  let count = 0

  for (let z = 0; z < group.order; z++) {
    let central = true

    for (let g = 0; g < group.order && central; g++) {
      central = group.product[z * group.order + g] === group.product[g * group.order + z]
    }

    count += central ? 1 : 0
  }

  return count
}

export type FiniteGaugeLattice = {
  readonly form: 'finite-gauge-lattice'
  readonly group: FiniteGroup
  readonly geometry: Hypercubic
  readonly links: Int16Array
}

export function makeFiniteGaugeLattice(input: {
  group: FiniteGroup
  lengths: readonly number[]
  start: 'cold' | 'hot'
  rng: Rng
}): FiniteGaugeLattice {
  const geometry = makeHypercubic({ lengths: input.lengths })
  const links = new Int16Array(geometry.sites * geometry.dim)

  if (input.start === 'hot') {
    for (let k = 0; k < links.length; k++) {
      links[k] = Math.floor(input.rng.next() * input.group.order)
    }
  }

  return { form: 'finite-gauge-lattice', group: input.group, geometry, links }
}

// One heatbath sweep: each link drawn over the whole group from exp(-S_local), where each of the six
// plaquettes through the link is U s for its staple s (a group element, the product of the other
// three links), so every plaquette is one table lookup. The action is the Wilson one plus, with
// beta1, the Re Tr U_p^2 term of Alexandru et al. (2019),
//
//   -S = sum over plaquettes of ((beta / 3) Re Tr U_p + beta1 Re Tr U_p^2)
//
// which at negative beta1 narrows the gap between the identity and its nearest elements and so moves
// the freezing to weaker coupling.
export function finiteHeatbathSweep(input: {
  lattice: FiniteGaugeLattice
  beta: number
  beta1?: number
  rng: Rng
}): void {
  const { lattice, beta, rng, beta1 = 0 } = input
  const { group, geometry, links } = lattice
  const { dim, sites, up, down } = geometry
  const { order, product, inverse, trace } = group
  const mul = (a: number, b: number): number => product[a * order + b] ?? 0
  // the plaquette weight of each element, (beta / 3) Re Tr g + beta1 Re Tr g^2
  const weightOf = Float64Array.from(
    { length: order },
    (_, g) => (beta / 3) * (trace[g] ?? 0) + beta1 * (trace[mul(g, g)] ?? 0),
  )
  const staples = new Int32Array(2 * (dim - 1))
  const weights = new Float64Array(order)
  const action = new Float64Array(order)

  for (let site = 0; site < sites; site++) {
    for (let mu = 0; mu < dim; mu++) {
      const siteUp = up[site * dim + mu] ?? 0
      const link = (s: number, d: number): number => links[s * dim + d] ?? 0
      const inv = (g: number): number => inverse[g] ?? 0
      let count = 0

      for (let nu = 0; nu < dim; nu++) {
        if (nu === mu) {
          continue
        }

        // forward: U_nu(x + mu) U_mu(x + nu)^-1 U_nu(x)^-1
        staples[count++] = mul(mul(link(siteUp, nu), inv(link(up[site * dim + nu] ?? 0, mu))), inv(link(site, nu)))

        // backward: U_nu(x + mu - nu)^-1 U_mu(x - nu)^-1 U_nu(x - nu)
        const below = down[site * dim + nu] ?? 0

        staples[count++] = mul(mul(inv(link(down[siteUp * dim + nu] ?? 0, nu)), inv(link(below, mu))), link(below, nu))
      }

      let largest = Number.NEGATIVE_INFINITY

      for (let g = 0; g < order; g++) {
        let sum = 0

        for (let k = 0; k < count; k++) {
          sum += weightOf[product[g * order + (staples[k] ?? 0)] ?? 0] ?? 0
        }

        action[g] = sum
        largest = Math.max(largest, sum)
      }

      let total = 0

      for (let g = 0; g < order; g++) {
        const w = Math.exp((action[g] ?? 0) - largest)

        weights[g] = w
        total += w
      }

      let pick = rng.next() * total
      let chosen = 0

      while (chosen < order - 1 && pick > (weights[chosen] ?? 0)) {
        pick -= weights[chosen] ?? 0
        chosen += 1
      }

      links[site * dim + mu] = chosen
    }
  }
}

// The mean plaquette Re Tr U_p / 3.
export function finitePlaquette(input: { lattice: FiniteGaugeLattice }): number {
  const { group, geometry, links } = input.lattice
  const { dim, sites, up } = geometry
  const { order, product, inverse, trace } = group
  const mul = (a: number, b: number): number => product[a * order + b] ?? 0
  let sum = 0
  let count = 0

  for (let site = 0; site < sites; site++) {
    for (let mu = 0; mu < dim; mu++) {
      for (let nu = mu + 1; nu < dim; nu++) {
        const a = links[site * dim + mu] ?? 0
        const b = links[(up[site * dim + mu] ?? 0) * dim + nu] ?? 0
        const c = inverse[links[(up[site * dim + nu] ?? 0) * dim + mu] ?? 0] ?? 0
        const d = inverse[links[site * dim + nu] ?? 0] ?? 0

        sum += (trace[mul(mul(mul(a, b), c), d)] ?? 0) / 3
        count += 1
      }
    }
  }

  return sum / count
}
