// The Higgs mechanism for a real scalar with the Mexican-hat potential
//   V(phi) = -mu2 phi^2 + lambda phi^4.
// For mu2 > 0 the minimum sits at a nonzero vacuum value v = sqrt(mu2 / 2 lambda) (broken
// symmetry); for mu2 <= 0 it sits at v = 0 (symmetric). The Higgs boson mass squared is the
// curvature V''(v) = -2 mu2 + 12 lambda v^2 (= 4 mu2 in the broken phase). A gauge field coupled
// with strength g eats the Goldstone mode and gains the mass term m = g v.

// The vacuum expectation value of V = -mu2 phi^2 + lambda phi^4.
export function mexicanHatVacuum(mu2: number, lambda: number): number {
  return mu2 > 0 ? Math.sqrt(mu2 / (2 * lambda)) : 0
}

// The Higgs boson mass squared, the curvature of the potential at the minimum:
//   V''(v) = -2 mu2 + 12 lambda v^2.
export function higgsBosonMassSquared(
  mu2: number,
  lambda: number,
): number {
  const v = mexicanHatVacuum(mu2, lambda)
  return -2 * mu2 + 12 * lambda * v * v
}

// The gauge-boson mass term m = g v generated by the Higgs vacuum value v at coupling g.
export function gaugeBosonMass(
  coupling: number,
  vacuumValue: number,
): number {
  return coupling * vacuumValue
}
