// The spin-exchange unitary on two charge-qubits, generated by H = XX + YY, applied at angle theta.
// It acts only on the {|01>, |10>} subspace (indices 1 and 2 of the 4-amplitude state): |01> -> c|01>
// - i s|10> and |10> -> c|10> - i s|01>, with c = cos(2 theta), s = sin(2 theta). At theta = pi/8 a
// product input |01> becomes the maximally entangled (|01> - i|10>)/sqrt(2). At theta = 0 it is the
// identity. The state is stored as parallel real and imaginary amplitude arrays, mutated in place.

export function applyExchangeUnitary(input: {
  re: Float64Array
  im: Float64Array
  theta: number
}): void {
  const { re, im, theta } = input
  const c = Math.cos(2 * theta)
  const s = Math.sin(2 * theta)
  const r1 = re[1]!
  const i1 = im[1]!
  const r2 = re[2]!
  const i2 = im[2]!
  re[1] = c * r1 + s * i2
  im[1] = c * i1 - s * r2
  re[2] = c * r2 + s * i1
  im[2] = c * i2 - s * r1
}
